### ISSUE TITLE
cannot display 3D file 

### ISSUE THREAD

**Issue by nur921606** [tpaviot/pythonocc-core#1021]
Hello Sir,

I have question to ask regarding display 3D autocad file. My 3D autocad file is in .stl file and the size is big. I wanted to display in pyqt5. When I used the big stl file seems like it cannot display the file. Is it possible to display for big file?

**Comment by ShieKn** [comment]
@tpaviot  i have the same question too ! i just want display that big stl file

**Comment by tpaviot** [comment]
Yes it is, see https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_mesh_data_source.py This is a recent addition allowing to quickly load big stl files
