### ISSUE TITLE
 PySide2.QtOpenGL.QGLWidget called with wrong argument types 

### ISSUE THREAD

**Issue by loukitkhemka** [tpaviot/pythonocc-core#1024]
I am getting the following error when running the qt demo with pyside2 backend:

 PySide2.QtOpenGL.QGLWidget called with wrong argument types

Any solution for this?

**Comment by tpaviot** [comment]
Can you please copy/paste the full trace, I need to know the script/line numbers

**Comment by tpaviot** [comment]
The pyside2 test passes, outdated isse.
