### ISSUE TITLE
Request for the support for IVTK

### ISSUE THREAD

**Issue by lokit-iscitech** [tpaviot/pythonocc-core#1027]
I was hoping if you could add support for IVTK library of OCC because then we could have OCC and VTK connection out of the box.

**Comment by tpaviot** [comment]
There already is a VTK support from the OCC library ,but it is not covered by the pythonocc-core wrapper. This issue/feature request should be posted to the official OTT issue tracker https://dev.opencascade.org/resources/issue_tracker
