### ISSUE TITLE
Documentation lines from other functions seem to be getting tacked onto these

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#103]
[gp_Vec.Multiplied](http://api.pythonocc.org/OCC.gp.html#OCC.gp.gp_Vec.Multiplied): "Multiplies a vector by a scalar Divides a vector by a scalar"

[gp_Vec.SquareMagnitude](http://api.pythonocc.org/OCC.gp.html#OCC.gp.gp_Vec.SquareMagnitude): "Computes the square magnitude of this vector. Adds two vectors"

[gp_Vec.Subtracted](http://api.pythonocc.org/OCC.gp.html#OCC.gp.gp_Vec.Subtracted): "Subtracts two vectors Multiplies a vector by a scalar"

Thanks to Jeremy Wright for reporting

**Comment by tpaviot** [comment]
This is an issue from OCE itself. For instance, in gp_Vec.hxx, you can find the following lines:
<pre>
//! Subtracts two vectors <br>//! Multiplies a vector by a scalar <br>
gp_Vc Subtracted(const gp_Vec& Right) const;
gp_Vec operator -(const gp_Vec& Right) const
{
     return Subtracted(Right);
}
</pre>

Please report issue either to OCE github repository or official OCC dev portal.
