### ISSUE TITLE
Question about LGPL

### ISSUE THREAD

**Issue by math-artist** [tpaviot/pythonocc-core#1030]
Hi,

I am currently planning to use pythonocc, exclusively for its ability to import CAD models (currently only using the step reader). This is a closed source project, and I am trying to be compliant with the license. It is currently easy for me to keep the OCC dlls external, but I am using a different Python compiler for packaging, and it is very challenging to keep Python code outside the executable (no solution yet), since it has to be packaged with the interpreter to make a standalone.

Is this project LGPL only because OpenCascade is LGPL? I mean, is it possible to package the Python code of pythonocc-core for a commercial project, and keep the OpenCascade libraries external? Merci.

**Comment by tpaviot** [comment]
pythonocc was licensed under the LGPL license before occt officially moved to this licence. You can redistribute pythonocc-core as well as occt libraries in your commercial project, as long as follow the license terms. Especially, each modification to pythonocc-core and/or occt has to be redistributed under the LGPL terms. If there's not any change to the library core, then you can just distribute binary packages.
