### ISSUE TITLE
Class Graphic3d_TransformPers not wrapped

### ISSUE THREAD

**Issue by cedricadam2** [tpaviot/pythonocc-core#1069]
Class Graphic3d_TransformPers not wrapped in pythonocc-core 7.5.1

**Comment by tpaviot** [comment]
confirmed, it is explicitly excluded from the wrapper, I have to check the reason why

**Comment by cedricadam2** [comment]
ok, i'll try to compile master branch and run it to check.

**Comment by cedricadam2** [comment]
@tpaviot I confirm, I can use the `Graphic3d_TransformPers` class in the current master branch.
