### ISSUE TITLE
Spring shape generation failed

### ISSUE THREAD

**Issue by luoyu-123** [tpaviot/pythonocc-core#1094]
I want to generate a shape of a spring, but when I scan along the thread using the BRepOffsetAPI_MakePipe function the model is incomplete and I don't know what's wrong. The version I am using is 7.4.0
The picture is as follows：

![image](https://user-images.githubusercontent.com/59160360/160341274-be41e728-0295-4bad-9890-9a89cdb77034.png)

**Comment by cafhach** [comment]
Looks like the spring is fully created but it only visualizes every second segment as a mesh and the others using a simplified style. Can you show your code to visualize the object?

**Comment by luoyu-123** [comment]
Thank you very much for your help, this and the problem have been solved on my side. It is a tolerance parameter mode that is set for less entities generated by scanning


![image](https://user-images.githubusercontent.com/59160360/164884426-44ea89ef-c883-4e34-97c9-920e71047ed5.png)


best wishes！
