### ISSUE TITLE
How to fund this project?

### ISSUE THREAD

**Issue by cafhach** [tpaviot/pythonocc-core#1132]
Hi there, my company is starting a funding program for FOSS projects relevant to the business. I would like to propose pythonocc, but one requirement is that

`the project must have some mechanism for receiving funds, e.g. via PayPal, Liberapay, Patreon, GitHub Sponsors, Open Collective, or a bank account.`

Is there a way to financially support the project?

**Comment by tpaviot** [comment]
thanks @cafhach for your support and the proposal. I created an account at opencollective and added a sponsor button to the top of the project page https://opencollective.com/pythonocc-core
