### ISSUE TITLE
Install pythonocc-core=7.7.0 using conda does not working

### ISSUE THREAD

**Issue by madureirabrazil** [tpaviot/pythonocc-core#1162]
I followed the instructions to install using conda and it was not possible to find pythonocc-core=7.7.0:

(pyoccenv) C:\Users\madureira>conda install -c conda-forge pythonocc-core=7.7.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pythonocc-core=7.7.0

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by tpaviot** [comment]
conda-forge packages for 770 are on the way

**Comment by tpaviot** [comment]
packages vailable
