### ISSUE TITLE
STEP file compound naming problem

### ISSUE THREAD

**Issue by CurssedCoffin** [tpaviot/pythonocc-core#1165]
I'm using core_load_step_with_colors.py to resolve the structure of names of a step file.
I get the names using function GetLabelName() of a label.
But it sometimes returns "COMPOUND" or "SOLID" as the name.
As other software like 3d-tool that compound does actually have a name.
I wonder is there any way to solve this naming problem.
Thank you!

**Comment by dpasukhi** [comment]
Hello, there is a not possible for now.
The name that you see is a automating names.

OCCT working on the soluting with extracting faces and compaunds names from the file, but for now only assembly elements are named.
