### ISSUE TITLE
DisplayMessage 

### ISSUE THREAD

**Issue by thnszgns** [tpaviot/pythonocc-core#1167]
I have some issues while trying to show text in my viewer.. End goal is to have a solid and show one number in each vertex (1,2,3,......)
I currently do it like this:
_self.display.DisplayMessage(gp_Pnt(10, 10, 10), 1)_

My problems is that I have tried everything I found but there seems to be no way to delete all these messages.. I am trying _self.display.EraseAll()_  and everything that has to do with erase and Remove in the display, viewer or context but nothing works. All the other shapes showed with DisplayShape are successfully removed

**Comment by tnakaicode** [comment]
I have same problem.
I solve this way:

```
text = display.DisplayMessage(gp_Pnt(0,0,0), "text0")
...
text.Clear()
text = display.DisplayMessage(gp_Pnt(0,0,0), "text1")
...
```

```display.DisplayMessage()``` return ```Graphic3d_Structure()```.

**Comment by thnszgns** [comment]
ok solved! Thank you very much for your time!
