### ISSUE TITLE
fuse problem /step export

### ISSUE THREAD

**Issue by JM-HH** [tpaviot/pythonocc-core#1193]
Hello,

I create several trees in a loop wich are composed from pipes and spheres. 
The export to STEP works fine, except I got a lot of bodies which is a problem for the simultion program.  Therefore I want to merge the spheres and pipes of each tree with **BRepAlgoAPI_Fuse**.  I collect the spheres and the pipes in seperate **TopTools_ListOfShape** and fuse them. But always _one_ of the trees is created faulty. The other trees are OK.

Is there a trick to fuse a large number of shapes or is there an other way to merge the shapes for STEP export?

![31-03-23_14-38_681](https://user-images.githubusercontent.com/82896633/229122846-4f1828ad-1470-4e68-b887-c74bccec0e5a.png)

**Comment by tpaviot** [comment]
Boolean ops at occt are known to be sometimes buggy or long to be processed
