### ISSUE TITLE
BVH of pythonocc

### ISSUE THREAD

**Issue by linbeijianbaoxia** [tpaviot/pythonocc-core#1205]
![image](https://user-images.githubusercontent.com/50166977/236610212-8c93d810-be00-4a10-8443-bd9e96a9ca79.png)
Is BVH package of OCCT not yet wrapped in pythonocc currently?

**Comment by tpaviot** [comment]
BVH package is actually wrapped but most classes are skipped. I remember it caused a lot of issues, but I didn't get back on this topic for a while. Noone so far requested support for this class, which class method needs it?

**Comment by linbeijianbaoxia** [comment]
> BVH package is actually wrapped but most classes are skipped. I remember it caused a lot of issues, but I didn't get back on this topic for a while. Noone so far requested support for this class, which class method needs it?

I need to use these classes: BVH_PrimitiveSet, BVH_Vec3d, BVH_Box, BVH_BinnedBuilder. I implemented BVH construction through OCC in C++, but it seems that I need to rewrite it in Python using pythonocc. I know that these classes also inherit from some base classes, and the encapsulation workload of these classes is huge, so I will try to build BVH from scratch in Python. Thank you very much for your selfless contribution to pythonocc.
