### ISSUE TITLE
Error: gp_Pnt is not defined

### ISSUE THREAD

**Issue by AmitBedaka** [tpaviot/pythonocc-core#122]
I am trying to run the Bottle.py code in OCC 6.9 in Ubuntu to understand the PythonOCC. Its more challenging to understand the class and it uses. Can anyone please suggest me the possible way to understand pythonocc. It will be great help for me. Kindly give ur valuable time to reply on email: akbedaka@gmail.com.

**Comment by jf---** [comment]
Traceback please?

**Comment by tpaviot** [comment]
@AmitBedaka Invalid issue report. Please report a reduced scope question/issue with precise description.

**Comment by AmitBedaka** [comment]
Thank you for your kind reply. I need to do my research using PythonOCC. I
am trying to solve bottle.py example but I am not able to execute it using
PythonOCC in Ubuntu. Kindly give your valuable time and suggestions.

Thanking you,

Kind regards,


*Amit Kumar Bedaka*
*M.Des (Mechanical System Design)*



*Indian Institute of Information Technology Design and Manufacturing,
Kancheepuram, (Institute of National Importance / Center of Excellence,
MHRD Govt of India)Chennai - 600 127, *
*Tamil Nadu, INDIA.*

**Comment by AmitBedaka** [comment]
Can anyone help me to sort out the above issues?

**Comment by tpaviot** [comment]
OCC 6.9 is not supported by pythonocc-0.16.x. You *must* download/install oce-0.16 or oce-0.16.1

**Comment by AmitBedaka** [comment]
Thank you for your kind reply.
ᐧ


*Amit Kumar Bedaka*
*M.Des (Mechanical System Design)*



*Indian Institute of Information Technology Design and Manufacturing,
Kancheepuram, (Institute of National Importance / Center of Excellence,
MHRD Govt of India)Chennai - 600 127, *
*Tamil Nadu, INDIA.*

**Comment by tpaviot** [comment]
Download here: https://github.com/tpaviot/oce/releases/tag/OCE-0.16.1
