### ISSUE TITLE
Is OCC.Core.Exception.ClassNotWrappedError: Poly_CoherentTriangulation not wrapped?

### ISSUE THREAD

**Issue by linbeijianbaoxia** [tpaviot/pythonocc-core#1221]
I try to use Poly_CoherentTriangulation, but get a error "OCC.Core.Exception.ClassNotWrappedError: Poly_CoherentTriangulation not wrapped"。

**Comment by tpaviot** [comment]
This class is actually excluded from the wrapper, I have to check if it works using a more recent occt version

**Comment by tpaviot** [comment]
Fixed by commit 410aec3b3cb9c67b2eb45c1427e80f14a125b868
