### ISSUE TITLE
RWPly is missing in version 7.7.0

### ISSUE THREAD

**Issue by rashikoz** [tpaviot/pythonocc-core#1241]
Hi All,

I have installed pythonocc 7.7.0 via conda and RWPly module is missing in the package. 
![RWPlyMissing](https://github.com/tpaviot/pythonocc-core/assets/7281383/ad6a4815-12b4-4c2c-af55-057f90f73eb8)

Thanks and Regards
Rashik

**Comment by tpaviot** [comment]
It is currenly available in the master branch https://github.com/tpaviot/pythonocc-core/blob/master/src/SWIG_files/wrapper/RWPly.i
