### ISSUE TITLE
Tags for versions 7.7.1 and 7.7.2 to enable updated conda-forge builds

### ISSUE THREAD

**Issue by Krande** [tpaviot/pythonocc-core#1242]
Hey! 

I was wondering if anyone could create release tags for pythonocc-core supporting opencascade v7.7.1 and v7.7.2? 
That way we can generate updated releases on conda-forge? (the latest tag today is 7.7.0 -> https://github.com/tpaviot/pythonocc-core/tags)

Best Regards
Kristoffer

**Comment by tpaviot** [comment]
I don't plan any 7.7.1 tag. Current master is being polished before 7.7.2 is tagged. There are some small api changes, have to be sure that there's no regression.

**Comment by Krande** [comment]
@tpaviot Sounds good! Then I'll wait for a tagged release of 7.7.2.

Best Regards
Kristoffer
