### ISSUE TITLE
Compile and install from source without touching /usr/local/lib/python*

### ISSUE THREAD

**Issue by ornamentist** [tpaviot/pythonocc-core#1262]
I'm compiling and installing pythonocc-core from source on an M1 mac. The build goes well until the "make install" stage when the makefiles want to install to `/usr/local/lib/python*`.

This is not the correct lib directory for Homebrew installed python on macOS. 

What's the correct setting or environment variable to override this behaviour? I've tried `-DINSTALL_DIR=...` without success.

**Comment by tpaviot** [comment]
try `-DPYTHONOCC_INSTALL_DIR`

**Comment by tpaviot** [comment]
yes

**Comment by tpaviot** [comment]
@ornamentist Did that solve the issue?

**Comment by ornamentist** [comment]
No, but I will revisit the problems after learning more about cmake.
