### ISSUE TITLE
Shape similarity between step files

### ISSUE THREAD

**Issue by serhatBilal** [tpaviot/pythonocc-core#1266]
With the pythonocc package I need, I want to open step files and access the geometric properties of these files. The purpose of this is to find the step files that are geometrically most similar to the step file I give as a parameter from the hundreds of step files I have. I don't know if I should search according to their geometric properties, but all I want is similarity, in fact I can accept a different method. but I couldn't find many sources and examples on this subject. I am waiting for your answer and comment, thank you. I wish you success in your work.

**Comment by tpaviot** [comment]
The answer depends on what you mean by "similarity." I recommend that you browse the scientific literature on this topic. Please reopen the ticket if ever you find something interesting.
