### ISSUE TITLE
Error: glTF writer is unavailable - OCCT has been built without RapidJSON support [HAVE_RAPIDJSON undefined]

### ISSUE THREAD

**Issue by varupala** [tpaviot/pythonocc-core#1272]
Followed instructions from install.md to build OpenCascade 7.7.2 and pythonocc. After running run_tests.py file, I got this error "Error: glTF writer is unavailable - OCCT has been built without RapidJSON support [HAVE_RAPIDJSON undefined]". Also I got the error "six module not found" when running simple test.

**Comment by tpaviot** [comment]
thank you for your feedback, indeed building with HAVE_RAPIDJSON is mandatory if you want to benefit from the gltx exporter/importer, and six is a python package required as well

**Comment by tpaviot** [comment]
FYI, in the Install.md file, it is explicitly told that rapidjson is a required dependency
