### ISSUE TITLE
Fail to import TColgp_Array2OfPnt

### ISSUE THREAD

**Issue by MindLostGuy** [tpaviot/pythonocc-core#1273]
I can successfully import TColgp_HArray1OfPnt, TColgp_Array1OfPnt, TColgp_HArray2OfPnt from OCC.Core.TColgp.
But I fail to import TColgp_Array2OfPnt.
I'm on a Linux, with python3.7 and Pythonocc core 7.4.1

**Comment by tpaviot** [comment]
Please update to the latest pythonocc-core release (7.7.2):
```bash
>>> from OCC import VERSION
>>> VERSION
'7.7.2'
>>> from OCC.Core.TColgp import TColgp_Array2OfPnt
>>> from OCC.Core.gp import gp_Pnt
>>> t = TColgp_Array2OfPnt(2,2)
>>> t.SetValue(2,2, gp_Pnt(1,2,3))
>>> t.Value(1,1).X()
0.0
>>> t.Value(2,2).X()
1.0
```
