### ISSUE TITLE
PyQt6 methods not compatible with PyQt5 or PySide2

### ISSUE THREAD

**Issue by Tanneguydv** [tpaviot/pythonocc-core#1280]
see https://github.com/tpaviot/pythonocc-core/commit/cc54af4c82c52c56282bfe9499df864aab8f24fc#commitcomment-133146386

**Comment by Tanneguydv** [comment]
Ok, it was a writing error in the code, `Button` instead of `MouseButton` on line 344 in _QtDisplay.py_

**Comment by tpaviot** [comment]
Good catch!
