### ISSUE TITLE
The way XCAFDoc_ColorTool works has changed

### ISSUE THREAD

**Issue by ICO-Fantasy** [tpaviot/pythonocc-core#1289]
I upgraded my pyocc from 7.7.0 to 7.7.2
I have put the following code
```
doc_str = TCollection_ExtendedString("doc")
doc = TDocStd_Document(doc_str)
shape_tool = XCAFDoc_DocumentTool_ShapeTool(doc.Main())
color_tool = XCAFDoc_DocumentTool_ColorTool(doc.Main())
```
replace with
```
doc = TDocStd_Document("doc")
shape_tool = XCAFDoc_DocumentTool.ShapeTool(doc.Main())
color_tool = XCAFDoc_DocumentTool.ColorTool(doc.Main())
```
The method `color_tool.GetInstanceColor(shape, 0, c)` works fine but color_tool.GetColor(label, 0, c) doesn't, what is the reason for this?
![image](https://github.com/tpaviot/pythonocc-core/assets/48787566/65c24092-2597-498c-974c-f0044250810e)
I am attaching the code that works fine in pyocc 7.7.0, it does not work in pyocc 7.7.2.
[readStepWithColor.txt](https://github.com/tpaviot/pythonocc-core/files/13542429/readStepWithColor.txt)

**Comment by daniel1v** [comment]
It seems like you can get the color with XCAFDoc_ColorTool.GetColor(), instead of color_tool.GetColor().

**Comment by ICO-Fantasy** [comment]
> It seems like you can get the color with XCAFDoc_ColorTool.GetColor(), instead of color_tool.GetColor().
> 
> @tpaviot is this intended behaviour?

![image](https://github.com/tpaviot/pythonocc-core/assets/48787566/9a16459d-d244-4657-bdd7-c4b1bf09a059)
The `color_tool` I'm using is defined like this. I don't think I can create an instance of XCAFDoc_ColorTool without XCAFDoc_DocumentTool.

**Comment by daniel1v** [comment]
> > It seems like you can get the color with XCAFDoc_ColorTool.GetColor(), instead of color_tool.GetColor().
> > @tpaviot is this intended behaviour?
> 
> ![image](https://private-user-images.githubusercontent.com/48787566/297105364-9a16459d-d244-4657-bdd7-c4b1bf09a059.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0Mjc2MjksIm5iZiI6MTcwNTQyNzMyOSwicGF0aCI6Ii80ODc4NzU2Ni8yOTcxMDUzNjQtOWExNjQ1OWQtZDI0NC00NjU3LWJkZDctYzRiMWJmMDlhMDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE3NDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTgwODEyZmFhMDNhYjkzNDA5NmMzNjFjM2E3ZGU4NjM1YTNlY2Q5NzdiNTViMmM2MjI5YWYzOWJjNDI5Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FHX2XW54utU2KlsgG-lM_01rqGDwqjOwHUsV_-59WcM) The `color_tool` I'm using is defined like this. I don't think I can create an instance of XCAFDoc_ColorTool without XCAFDoc_DocumentTool.

You do not have to create an instance. Just call the function.

**Comment by ICO-Fantasy** [comment]
> daniel1v

Thank you very much, dear daniel1v. The method you provided does work. In the pyocc source code, the XCAFDoc_ColorTool.GetColor method does not use the @staticmethod decorator, but calling it directly is effective. Following your advice, the code is now running correctly.

**Comment by daniel1v** [comment]
> > daniel1v
> 
> Thank you very much, dear daniel1v. The method you provided does work. In the pyocc source code, the XCAFDoc_ColorTool.GetColor method does not use the @staticmethod decorator, but calling it directly is effective. Following your advice, the code is now running correctly.

Yeah, that confused me too.
