### ISSUE TITLE
Update PPA for Ubuntu 15.04 ?

### ISSUE THREAD

**Issue by stuaxo** [tpaviot/pythonocc-core#129]
Hi,
   Is there any chance of updating the PPA for Vivid (15.04) ?

S

**Comment by tpaviot** [comment]
I didn't work on the ppa part for a while, it's on my todo list.

**Comment by jf---** [comment]
@tpaviot , shall we point to conda rather than offering distro specific packages?

**Comment by stuaxo** [comment]
If you are doing that, would it be possible to make a version installable from pip ?

**Comment by jf---** [comment]
hi @stuaxo , nope, that's beyond the technical scope of pip...
we support binary installation ( pythonocc + dependencies ) [through conda](https://anaconda.org/DLR-SC). there's only so much you can do in terms of installing dependencies in pip, hence conda.

**Comment by tpaviot** [comment]
Please use conda.

**Comment by stuaxo** [comment]
Cheers, unfortunately every time I've tried conda it doesn't have the things in it I like to use.

If I play try pythonocc in the future I might have a look at getting pythonocc working with vext (a horrible hack I've made to make things that don't work in virtualenv accessible from virtualenv).
