### ISSUE TITLE
DumpJsonToString missing from type stubs

### ISSUE THREAD

**Issue by anuraaga** [tpaviot/pythonocc-core#1294]
I noticed that type stubs seem to be missing `DumpJsonToString`, so for example pyright raises an error when using that method. I only checked `Shape` but think it affects all the types

https://github.com/tpaviot/pythonocc-core/blob/37ec91c0e7dfb6da4aa13240a86b9740ddaf07a6/src/SWIG_files/wrapper/TopoDS.pyi#L176

Could it be added to the types?

**Comment by tpaviot** [comment]
This might be fixed by #1301 , merged into master. Can you please test and close the issue if successful?
