### ISSUE TITLE
RuntimeError: Aspect_DisplayConnectionDefinitionErrorCan not connect to the server "" raised from method Display3d of class Display3d

### ISSUE THREAD

**Issue by Lydiagugugaga** [tpaviot/pythonocc-core#1302]
Dear community,
    My problem is "can't use the class` Viewer3d()`  `from OCC.Display.OCCViewer import Viewer3d`
  
  `viewer = Viewer3d()`  <-- `Display3d.__init__(self)`   <-- `_Visualization.Display3d_swiginit(self, _Visualization.new_Display3d())`
  `RuntimeError: Aspect_DisplayConnectionDefinitionErrorCan not connect to the server "" raised from method Display3d of class Display3d`
  
  The version is pythonocc-core=7.7.2
  
  I can do it in windows, but it can't work  in linux. `viewer = Viewer3d()`
How to solve this problem for using in linux?
I wish for your help.

**Comment by vinnyvimto** [comment]
So running the [offscreen rendering example](https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_offscreen_rendering.py), which uses the Viewer3d, I have it working fine. This was with
- ubuntu 23.10
- python 3.10
- pythonocc-core 7.7.2

Annoyingly though when I try to run this in a ubuntu:23.10 docker container with the exact same dependencies I get the above error. Would love to know a way around it so I can run workloads with it in docker.

**Comment by tpaviot** [comment]
On Linux, to instanciate the ```Viewer3d``` class, you need to have a x server installed, or an x server emulator (like xvfb)
