### ISSUE TITLE
how to display utf-8 text

### ISSUE THREAD

**Issue by ycyang77** [tpaviot/pythonocc-core#1308]
How do I display utf-8 text using the DisplayMessage method?

**Comment by tpaviot** [comment]
utf8 is supported. Can you please post an example and a screenshot

**Comment by ycyang77** [comment]
![1](https://github.com/tpaviot/pythonocc-core/assets/9064496/c5a82601-feaf-4a7e-8bee-77a1b6156ec3)

Thank you~

**Comment by ycyang77** [comment]
![1](https://github.com/tpaviot/pythonocc-core/assets/9064496/c5a82601-feaf-4a7e-8bee-77a1b6156ec3)

Thank you~

**Comment by ycyang77** [comment]
![1](https://github.com/tpaviot/pythonocc-core/assets/9064496/c5a82601-feaf-4a7e-8bee-77a1b6156ec3)

Thank you~

**Comment by tpaviot** [comment]
You did it the right way. Be sure you have the latest version installed.

![display_message_unicode](https://github.com/tpaviot/pythonocc-core/assets/660130/79473ba7-7aa8-449b-a0a4-1e6a14f99808)
