### ISSUE TITLE
How can I offset a curve on a surface

### ISSUE THREAD

**Issue by jiangotto** [tpaviot/pythonocc-core#1310]
I am using pythonocc to generate 3d printing tool path and I need to offset the edges of the surface. However, I find out that pythonocc 
can only offset 2d curves. I'm wondering how I can offset a curve on a sueface.

**Comment by tpaviot** [comment]
You need to use a ```BRepAdaptor```. Check https://github.com/tpaviot/pythonocc-demos/tree/master/examples

**Comment by jiangotto** [comment]
> You need to use a `BRepAdaptor`. Check https://github.com/tpaviot/pythonocc-demos/tree/master/examples

I've run all the demos, but none of them can offset curves on a surface(not a plane).
