### ISSUE TITLE
cannot import name 'BRepAdaptor_HCurve' from 'OCC.Core.BRepAdaptor'

### ISSUE THREAD

**Issue by sourav0208** [tpaviot/pythonocc-core#1377]
I am facing issues with  'BRepAdaptor_HCurve' and similarly with 'BRepAdaptor_Hsurface'. 

here is the error:
ImportError: cannot import name 'BRepAdaptor_HCurve' from 'OCC.Core.BRepAdaptor' 

what do I need to do? I am a beginner.

Thanks

**Comment by tpaviot** [comment]
`BRepAdaptor_HCurve` is not part of occt/pythonocc. It used to be. Use `BRepAdaptor_Curve` or `BRepAdaptor_Surface`
