### ISSUE TITLE
Inspection of two models and visualization

### ISSUE THREAD

**Issue by Bill-XU** [tpaviot/pythonocc-core#1389]
Hi @tpaviot ,

Sorry for bothering.
Please help answer one more simple question.

I am trying to create an inspection feature in my project.
The feature is for comparing two similar models and visualizing the differences with colors,
just like what inspection workbench does in FreeCAD.

I wrote a rough prototype using low-level APIs and achieved my goal with it.
But the performance is not so good.
I wonder if there are ready-to-use APIs that can help with that.

Could you help give some hints?

Best regards,
Bill

**Comment by tpaviot** [comment]
Your question is too wide, it cannot shorlty be answered here.
