### ISSUE TITLE
Default Value of linear_deflection 

### ISSUE THREAD

**Issue by ThisGuyIsNotAJumpingBear** [tpaviot/pythonocc-core#1390]
Hi,

I was wondering why the `linear_deflection` parameter in write_stl_file(), line 394 src/Extend/DataExchange.py, is set to 0.9 but claimed to be "default to 0.001" in the docstring? Thanks!

**Comment by tpaviot** [comment]
It's a mistake, thank you for the report.

**Comment by ThisGuyIsNotAJumpingBear** [comment]
Also, may I ask why 0.9 is selected here instead of 0.001? It seems that the current default value is decreasing the precision and making the final shape's quality worse.

**Comment by tpaviot** [comment]
I guess that the 0.001 value generates a *very* big file (it was a long time agot the last time I tweaked this part of the code). Default to 0.9 saves disk space and computation time, if you need better accuracy, you can change the default value to a lower one.

**Comment by Ma-Weijian** [comment]
Hi there,
I just wonder if the choice of the `linear_deflection` value affect the validity of the final mesh? Just something like setting `linear_deflection` increases the likelihood of obtaining a mesh instead of meeting an exception saying the shape is illegal?
