### ISSUE TITLE
platform.system() returns "Windows"

### ISSUE THREAD

**Issue by Bill-XU** [tpaviot/pythonocc-core#1392]
Hi @tpaviot 

Thank you for previous updates for windows users!

I found a small mistake here : [__init__.py@Ln.38](https://github.com/tpaviot/pythonocc-core/blob/3034d9febf8a181550a772d6d4321e9a34fee3db/src/PkgBase/__init__.py#L38)

* As is
```python
if platform.system() == "windows":
```

* Should be
```python
if platform.system().lower() == "windows":
```

* Reason
On Windows, platform.system() returns "Windows" in which there is a capital letter.
Should convert it to lower cases before matching.

Best regards,
Bill

**Comment by tpaviot** [comment]
Fixed by commit 85164196d93bcd8d8471ef4aec56efe501833a6f
