### ISSUE TITLE
new to pythonocc-core import lib error

### ISSUE THREAD

**Issue by maccardo** [tpaviot/pythonocc-core#1397]
I have built from source without errors pythonocc-core 7.8.1 with python 3.11.1 on windows 10.

Starting with the simple example
from OCC.Core.gp import gp_Pnt
p = gp_Pnt(1., 2., 3.)
p.X()

I get the following:
Exception has occurred: ImportError
DLL load failed while importing _gp: The specified module could not be found.
  File "D:\Tunnel\TunnelDataInspector\tunnelDataApp.py", line 1, in <module>
    from OCC.Core.gp import gp_Pnt
ImportError: DLL load failed while importing _gp: The specified module could not be found.

Any hints on what I am doing wrong. I do see _gp.pyd in the site-packages/occ tree.

Thanks
Marco

**Comment by maccardo** [comment]
solved problem by installing 3rd party libraries to occt

**Comment by sigurHeBin** [comment]
> solved problem by installing 3rd party libraries to occt

excuse me,I have the same problem as you. Can you tell me in detail how you solved it？how to  installing 3rd party libraries to occt？

thanks.Looking forward to your reply！

**Comment by 0make** [comment]
I solved this by copying all occ and its 3rd dlls to compiled pythonocc core directory
