### ISSUE TITLE
fillet produces strange shapes

### ISSUE THREAD

**Issue by Matrixxxxxxxx** [tpaviot/pythonocc-core#1402]
![Snipaste_2024-12-26_03-02-31](https://github.com/user-attachments/assets/124c7a77-6d8d-42ee-ada6-8455922954e5)
I have filled the top and bottom edges of the shape in the picture, but the result of fillet is a bit strange (not smooth and coherent). I want to know why? Is there a solution? Thank you

**Comment by Matrixxxxxxxx** [comment]
The top edge is obtained by simple extrude, and the bottom circular edge is obtained by revolve.

**Comment by tpaviot** [comment]
imho this is not related to pythonocc, but rather how the occt library computes fillets. You should report the use case to their issue tracker https://github.com/Open-Cascade-SAS/OCCT/issues. If you do think pythonocc is involved, please submit a python code that can be executed/debugged.

**Comment by Matrixxxxxxxx** [comment]
Thanks, I will report this case to OCCT
