### ISSUE TITLE
BUG: CSF_GraphicShr definition on windows wong librart filename

### ISSUE THREAD

**Issue by costishatzopoulos** [tpaviot/pythonocc-core#142]
**File:** src/addons/Display/OCCViewer.py
**Line:** 61

This is set to point to library *TKOpenGL.dll* while the correct (i think) is *TKOpenGl.dll*. I installed the python 27, 64bit installer of 0.16.2 and wxpython 3.0.2.0 and by correcting this everything seems to work again.

In my installation only file *libTKOpenGl.dll* exists. Also the comment in *Line 59* seems to verify this.

I'm not familiar with github and OpenCascade yet, so please excuse any glitches.

Regards,

**Comment by tpaviot** [comment]
You're right, fixed by commit 1e6cfd36509aeaa9d319fd47fea014d701444c93

However Windows is not case sensitive, it should not cause a segfault, I can't undersand. Anyway, thank you for this report
