### ISSUE TITLE
Need help doing the install pythonocc-core and OCE

### ISSUE THREAD

**Issue by 3wwebdev** [tpaviot/pythonocc-core#148]
Hi

Would I be able to ask if some one could do this install for me by remote PC?

Simon

**Comment by krontzo** [comment]
Which OS are you using?

**Comment by tpaviot** [comment]
@3wwebdev Can you please be more precise with the issue you face ?

**Comment by tpaviot** [comment]
Please use conda to install pythonocc in an easy way.
