### ISSUE TITLE
PAF framework

### ISSUE THREAD

**Issue by 3wwebdev** [tpaviot/pythonocc-core#149]
is their any documentation on PAF framework? or examples?

**Comment by jf---** [comment]
there are on the old outdate pythonocc repo.
PAF relied on the GEOM module, which hasnt been backported to the much sanitized current repo's.
So, file an issue for missing GEOM / PAF?

**Comment by tpaviot** [comment]
GEOM has not been updated for a while. At some point, it can be considered as outdated.
