### ISSUE TITLE
Where is TPrsStd package in new Release Pythonocc?

### ISSUE THREAD

**Issue by jonike** [tpaviot/pythonocc-core#151]
Hi, There!
I want to use OCAF applicaton framework to save the TPrsStd_AISPresentation class in my OCAF document. but i can't find _TPrStd.pyd in python site-packages/OCC directory.

Could anyone to give me some suggestions, please?
Thanks.

**Comment by jonike** [comment]
By the way, i found some warning in PCDM_StoreStatus. 
/*******
swig/python detected a memory leak of type 'PCDM_StoreStatus *', no destructor found.
******/
And there is no export TDataStd_Name_Set static function in TDataStd.py, you must manual to do it.
Sorry for my poor english.

**Comment by jf---** [comment]
@tpaviot , can you please close the issue?

**Comment by tpaviot** [comment]
Well, @jonike is right. The OCAF framework is not completely wrapped.

I suggest we keep this issue opened untill it's done. Let's postpone a complete ocaf support to oce-0.17 support.

**Comment by jonike** [comment]
Thanks guys. That's impressive! Great  job. I am waiting for good news.
