### ISSUE TITLE
BRep_Tool_Triangulation Nodes Length crashes if face is a triangle

### ISSUE THREAD

**Issue by jackcaron** [tpaviot/pythonocc-core#161]
if I have a piece of like this:
```
face = topods_Face(ex.Current())
location = TopLoc_Location()
facing = BRep_Tool_Triangulation(face, location).GetObject()

nodes = facing.Nodes()

nbPoints = facing.NbNodes() # <<-- crash
nbPoints = nodes.Length()   # <<-- crash
```
I use *TopExp_Explorer(face, TopAbs_EDGE)* to count the number of edges. So for now, if there's only three. I'm avoiding that part and extract manually the vertices. But I need to apply the inverse matrix of that shape to get them at the right position that I would normally get them with the triangulation.

Note that I'm getting this crash from a STEP file while I visit each SOLID and SHELL.

**Comment by jf---** [comment]
you might have to test whether a triangulation exists, before visiting it, eg, test whether nodes.IsNull()

**Comment by jackcaron** [comment]
I think I tried the *IsNull* function. I also used the *Checked* function and I'm still using *IsAllocated*.

**Comment by jf---** [comment]
do you have a more complete example to re-produce the problem?

**Comment by jackcaron** [comment]
I can try to find a simple example. The only file that has this bug is from a client, so I can't share it.

I'll look into it and try to make one.

**Comment by jf---** [comment]
@jackcaron ,

are you aware of pythonocc's [webgl support](https://github.com/tpaviot/pythonocc-core/blob/master/examples/core_webgl_threejs_torus.py) through threejs?

**Comment by jackcaron** [comment]
I've seen the files, never checked them. Is there an example in there to parse STEP with triangles?

**Comment by jf---** [comment]
Since it seems your interest is in webgl / that function implements what your after, its sure looking into I think...

STEP by definition should not encode a mesh, but BRep CAD data...
STL / OBJ / Collada are more commonly used for mesh data.

PythonOCC really deals with BRep, not mesh...

**Comment by tpaviot** [comment]
Closing the issue. The STEP file may be corrupted.
