### ISSUE TITLE
QML example missing

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#173]
a [very interesting example](https://youtu.be/kvWeE3kurEQ?t=6m9s) usage of QML in a 3d / CAD context

**Comment by tpaviot** [comment]
@jf--- what's the status of the QML example you talked about a few weeks ago ?

**Comment by jf---** [comment]
hi @tpaviot good enough for pythonocc-contrib, it depends on 0.17 support to work ( 0.17 could be a great label )

**Comment by tpaviot** [comment]
@jf--- does it work with current 0.17 branch ? In that case you can submit  pr based upon the 0.17 branch

**Comment by jf---** [comment]
@tpaviot , yep it does, I'll 1st commit a nr of fixes in Display3d.cpp & Visualization.h that are requires for QML to work

**Comment by tpaviot** [comment]
@jf--- what's the status of the qml example ?

**Comment by jf---** [comment]
Coming up, thanks for the reminder...

**Comment by tpaviot** [comment]
Issue opened a while ago, no progress, closing.
