### ISSUE TITLE
use python-versioneer for automated release versioning

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#190]
[see python-versioneer](https://github.com/warner/python-versioneer)

**Comment by tpaviot** [comment]
On the Versionneer page I can read:

"This is a tool for managing a recorded version number in distutils-based python projects".

pythonocc-core compilation/package is not managed by distutils. @jf--- can u please check it is distutils only and close the issue or leave it open but ensure this is compliant with any distribution system (for instance cmake).

**Comment by rainman110** [comment]
Here's a way, to integrate git information into the conda recipe version:
http://conda.pydata.org/docs/building/environment-vars.html#git-environment-variables

This almost suffices. We just need to integrate the git-sha into cmake, which can be done like this:
https://github.com/DLR-SC/tigl/blob/master/cmake/GetGitRevisionDescription.cmake

**Comment by jf---** [comment]
Lets keep it simple if we can ;)
