### ISSUE TITLE
DisplayMessage doesnt render text

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#193]
minimal example

```python

from OCC.gp import gp_Pnt
from OCC.Display.SimpleGui import init_display
display, start_display, add_menu, add_function_to_menu = init_display()


if __name__ == '__main__':
    P8 = gp_Pnt(-24, 120, 12.5)
    display.DisplayMessage(P8, "Does not show up")
    start_display()

```

**Comment by jf---** [comment]
Quite possible that this has something to do with the link issue to freeimage issue experienced installing possible specific to the DLR/SC osx binaries...

I dont believe this to be a pythonocc issue, but build related

**Comment by jf---** [comment]
tried with the current DLR/SC build ( 0.16.3 ), same thing...

**Comment by jf---** [comment]
better example: pythonocc-core/examples/core_topology_glue.py

**Comment by tpaviot** [comment]
works on my windows machine
![core_topology_glue](https://cloud.githubusercontent.com/assets/660130/12214775/df099b00-b6a1-11e5-9972-0f3cd4beb02f.PNG)

**Comment by jf---** [comment]
Yep, seems like this is an issue with the binary. I tried both my own built & DLR/SC, same result.

**Comment by efirvida** [comment]
I have the same Issue using python2.7 oce-16.1 python-occ 0.16.4 build from source in opensuse leap 42.1

**Comment by calocedrus** [comment]
This is closed and apparently not directly related to pythonocc but may I ask how to properly render text (using the nightly built, python 3.5 and linux, I observe the same as what @jf---  reported)? It seems that all convex characters (e.g. 0, a, B, 8,...) will show a strange behviour (characters replaced with vertical lines), but characters made of straight lines are fine (e.g. 1, i, l, k...)

**Comment by chavan-vjti** [comment]
Can I get to know, what exactly could be the linking issue with freeimage?
