### ISSUE TITLE
Travis-ci fails

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-core#215]
A small commit to master made travis build failed:
https://travis-ci.org/tpaviot/pythonocc-core/builds/106507941

 Any idea @rainman110 what's going on ?

**Comment by rainman110** [comment]
It seems, that conda can not get the version tag from git. I don't know why.

As a fallback, the version is set to an empty string:
```yml
version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}
```

Without a proper version, the package might be invalid / or have an invalid name. Thus, conda fails to install the freshly built package.

**Comment by tpaviot** [comment]
Ok, this fixes travis build.
