### ISSUE TITLE
enabling raytracing

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#223]
[ shoot, it looks like raytracing only works on osx on [OCC 6.9.0+](http://www.opencascade.com/content/open-cascade-technology-690-available-download) ]

Here is a minimal example, that tries to enable raytracing.
However, currently, rendering parameters cannot be altered.
Graphic3d_RenderingParams is probably not wrapped correctly.

```python
from __future__ import print_function

from OCC.BRepPrimAPI import BRepPrimAPI_MakeBox, BRepPrimAPI_MakeSphere
from OCC.Display.SimpleGui import init_display
from OCC.Graphic3d import *

display, start_display, add_menu, add_function_to_menu = init_display()

ais_boxshp = None

def build_shape():
    boxshp = BRepPrimAPI_MakeSphere(50.0).Shape()
    ais_boxshp = display.DisplayShape(boxshp, update=True)
    return ais_boxshp

build_shape()

render_params = Graphic3d_RenderingParams()

display.View.ChangeRenderingParams(render_params)

>>> TypeError: V3d_View_ChangeRenderingParams() takes exactly one argument (2 given)

start_display()

```

**Comment by jf---** [comment]
a bit of context from ``oce/samples/qt/Common/src/View.cxx``

```c++
  if (myIsRaytracing)
    myView->ChangeRenderingParams().Method = Graphic3d_RM_RAYTRACING;
}
```

**Comment by tpaviot** [comment]
ChangeRenderingParams is a c++ method that changes params by reference. The Graphic3d_RenderingParams is a bit special and needs a specific wrapper.

**Comment by tpaviot** [comment]
This is a hack to change the rendering method. In the file Graphic3d.i, add the following method to the Graphic3d_RenderingMethod (around line 5500):
````
%extend Graphic3d_RenderingParams {
	void SetRayTracing() {
		$self->Method = Graphic3d_RM_RAYTRACING;
	}
};
```
Recompile, and then modify your script as follows:
```
display.View.RenderingParams().SetRayTracing()
```

**Comment by tpaviot** [comment]
You can alse hack the Display3d class, to experiment:
```
myV3dView->SetWindow(myWindow);
++ myV3dView->ChangeRenderingParams().Method = Graphic3d_RM_RAYTRACING;
```

**Comment by jf---** [comment]
Yes, its really not very idiomatic code.
I like your idea of doing this in the Display3d class rather than is SWIG code for this reason.
Will look into this, thanks for the pointer Thomas...

**Comment by jf---** [comment]
will adress this in PR #238
