### ISSUE TITLE
AIS_ColoredShape not wrapped 

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#227]
OCE 0.17 has a new class AIS_ColoredShape, which is rather useful; it allows you to assign colors to subshapes of a TopoDS_Shape. So the complete imported geometry does not have to share a single color anymore ( just for analytical purpose ( rendering all faces with an area < threshold ) ) 

[API docs](http://www.opencascade.com/doc/occt-6.9.0/refman/html/class_a_i_s___colored_shape.html#a2ffabea78b9829940731e739acaa64f7)

**Comment by tpaviot** [comment]
@jf--- Is it a 0.16.x or 0.17.x issue ?

**Comment by jf---** [comment]
Hi Thomas, its a 0.17 specific issue. Sorry, I cannot label the issues...

**Comment by tpaviot** [comment]
Fixed by commit 17406be2ac759a1c8a157e975cf64910d963d381
