### ISSUE TITLE
automatic test of examples

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#244]
we've been thinking about using the examples as unit tests and to be able to run these automatically.

- to create test from the examples is easy, just add assert statement
- to bypass running the GUI, I suggest using a decorator for the functions to be tested
  - the decorator sets os.setenv("TEST_PYOCC", 1)
  - now, when loading `from OCC.Display.SimpleGui import init_display` we just return a mock object instead of a OCC.Display instance. Any method called simple wont perform any actions

test coverage of our examples would be a great thing to have, especially when working towards a new OCE release.

mo' code coverage mo' better...

**Comment by tpaviot** [comment]
test at https://github.com/tpaviot/pythonocc-core/tree/review/run-examples-as-tests

**Comment by jf---** [comment]
Cool! 
Happy to hear you think its worthwhile to further explore...
I'll start refactoring & placing __assert__ statement ( "assert SomeOperation.IsDone() ) for example

**Comment by tpaviot** [comment]
Done. See #258
