### ISSUE TITLE
gp_Vec can't be divided by float

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-core#257]
On python2/pythonocc-0.16.4
```
>>> from OCC.gp import gp_Vec
>>> gp_Vec(1,2,3)/2
<OCC.gp.gp_Vec; proxy of <Swig Object of type 'gp_Vec *' at 0x02B3A728> >
````

On python3:
```
>>> from OCC.gp import gp_Vec
>>> gp_Vec(1,2,3)/2
>>>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for /: 'gp_Vec' and 'int'
```
why ?

**Comment by tpaviot** [comment]
Note: on python3, other operators work (+,-,*).

**Comment by tpaviot** [comment]
This issue is related to SWIG-3*. Using SWIG-2*, it works as expected

**Comment by rainman110** [comment]
Could it be something with float vs integer division? Try:
```
gp_Vec(1,2,3)/2.
```
(with the dot after the 2)

**Comment by tpaviot** [comment]
It seems to be a SWIG 3 issue (see https://github.com/swig/swig/pull/617 and https://github.com/swig/swig/pull/136)

**Comment by tpaviot** [comment]
Note that a workaround is to replace
```
a_gp_Vec / a_float
```
with
```
a_gp_Vec * ( 1. / a_float)
```
same for integers

**Comment by rainman110** [comment]
@tpaviot Should we then stick to SWIG 2 for the packaging?

**Comment by tpaviot** [comment]
@rainman110 If possible yes

**Comment by rainman110** [comment]
@tpaviot  I just tested it with swig 2.0.10. There, I still get the error on python3:
```TypeError: unsupported operand type(s) for /: 'gp_Vec' and 'int'```
or
```TypeError: unsupported operand type(s) for /: 'gp_Vec' and 'float'```

**Comment by rainman110** [comment]
@tpaviot I just tested this issue with the newest swig 3.0.9. This fixes the issue.

What remains to be done is to rebuild all conda packages with the 3.0.9 version of swig.

**Comment by jf---** [comment]
nice find @rainman110 !

**Comment by rainman110** [comment]
I uploaded all python3 related packages.

@tpaviot The issue can be closed.

**Comment by jf---** [comment]
is there a unittest for gp_Vec division?

**Comment by tpaviot** [comment]
I added a unittest (see #278). @rainman110 I'll close the issue as soon as the test passes on travis.

**Comment by tpaviot** [comment]
Fixed. Thanks you @rainman110
