### ISSUE TITLE
cross section visualization example

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#260]
[see here](http://dev.opencascade.org/index.php?q=node/839), could be of interest with our GUI fascinations. I'll adapt from the DRAWEXE code.

![](http://dev.opencascade.org/sites/default/files/capping.png)

@aothms

**Comment by aothms** [comment]
Wow nifty. Is this a rendering step am I right, stencil buffer magic probably, no boolean ops involved?

**Comment by jf---** [comment]
Exactly... I guess with the WIP wrt new IFC gui's this might come in handy ;)
Warning, this might have a dependency on #5

**Comment by tpaviot** [comment]
@jf--- where's the source code ? I can't fint it

**Comment by jf---** [comment]
hi @tpaviot , so this is a visual reminder to self ( alas, can't "assign" issues  ) to create this example.

**Comment by tpaviot** [comment]
@jf--- any progress regarding this issue ?

**Comment by jf---** [comment]
@tpaviot not yet, of lesser urgence...

**Comment by tpaviot** [comment]
commit c0d6d5f adds an example using clipping plane

**Comment by tpaviot** [comment]
see https://youtu.be/qZhkGUvdAZU
