### ISSUE TITLE
Missing modules StepRepr, StepGeom, StepShape, StepToGeom, StepToTopoDS

### ISSUE THREAD

**Issue by brentlymills** [tpaviot/pythonocc-core#261]
Hello,

If possible could the following modules be added back to pythonocc StepRepr, StepGeom, StepShape, StepToGeom, and StepToTopoDS? They were present in pythonocc 0.6rc1.

Thank you very much for providing such a wonderful python implementation of Open CASCADE!

Brent #

**Comment by tpaviot** [comment]
Right, TKSTEPBase and TKSTEP packages are missing or not fully wrapped.

**Comment by tpaviot** [comment]
Fixed by #264
