### ISSUE TITLE
Decrease build time

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-core#267]
Building pythonocc-core is a long task. Continous Integration services have time limits (for instance travis is 50mn, appveyor 1h), and pythonocc-core builds exceed this limit. I tried to tweak the build (gcxx flags, Release/MinRelSie etc.) but unfortunately did not succeed to get significant results.

So far, I see the following solutions:

* ask travis an extra time. Done I will give here the answer from the travis-ci support

* Prebuild the cxx file on our Windows/Linux/OSX machines and push them to github. Thus skip the SWIG stage when building core. The cxx generation could be achieved by the pythonocc-generator

* use the cache systems of travis and appveyor to avoid SWIG'ing each time a new build is started. (SWIG should only be run whenever .i files are modified, actually this is what's happening when we build pythonocc-core on our machines).

* use ccache (https://ccache.samba.org/) as a compiler

**Comment by tpaviot** [comment]
I just asked an extra time to travis support this morning, they gave 20 more minutes ! That means the time limit is now 70minutes, which is just perfect for building everything needed.

**Comment by jf---** [comment]
Wow! That's a lot more convenient that having to deal with ccache ;)
Sweet...

**Comment by tpaviot** [comment]
I close the issue, no doubt it will have to be reopened in the midterm
