### ISSUE TITLE
feedback on pythonocc memory leak 

### ISSUE THREAD

**Issue by chenkianwee** [tpaviot/pythonocc-core#272]
Hi I am not sure this is the right place for feedback ? But I have given pythonocc 0.16.5 a go and tested it out on the problem I previously had a memory leak. It is working fine now.

**Comment by rainman110** [comment]
@chenkianwee I am glad to here this 😄 

Thanks for the feedback.

**Comment by chenkianwee** [comment]
sure, I should thank all of you for fixing the bug !! Thanks !!
