### ISSUE TITLE
Can't run x3dom rendering example

### ISSUE THREAD

**Issue by yoeldk** [tpaviot/pythonocc-core#280]
Hello,

I'm running the code of the rendering cylinder example, but the browser (firefox) shows nothing.
I checked it for x3dom rendering support and it does support it, but when running the code it doesn't show the shape.

Thanks in advance for all helpers,
Joel

**Comment by jf---** [comment]
whats the output of your console / command terminal?

**Comment by yoeldk** [comment]
There's no special output / error message...
It opens a firfox tab with the "correct" background (blue background with the text "python occ x3dom renderer" at the bottom left) but doesn't show the 3d shape at all.

**Comment by tpaviot** [comment]
@yoeldk Which browser version is it ? os ? pythonocc ?

A possible way to debug is to enable the Firefox (click Menu->Debugger->WebConsole). After enabling the webconsole, reload the webpage, you should see a log if ever there is an issue. Can you please copy/paste the issue here ?

**Comment by yoeldk** [comment]
![webconsole](https://cloud.githubusercontent.com/assets/12507451/15972658/7b019af2-2f48-11e6-8cc3-5176b529a5d6.png)

**Comment by yoeldk** [comment]
Update:
I'm using windows 7 with a firefox version 47.0 as my default browser.
As seen above, firefox does not render the shape but I copy-pasted the url into a chrome browser and there it worked fine..
I would still prefer to have it working on firefox as well.

**Comment by jf---** [comment]
thanks for the update @yoeldk , happy to hear you managed to make this work.
can I ask you to close the issue?

**Comment by tpaviot** [comment]
@jf--- no the issue should not be closed, @yoeldk wants to run FF47

**Comment by jf---** [comment]
ooops...

**Comment by tpaviot** [comment]
@yoeldk It seems you run pythonocc-0.16.3 which is outdated. Can you please update to the latest release 0.16.5 and check again

**Comment by yoeldk** [comment]
@tpaviot According to the following website I am running the latest software (0.16.3). What is the basis for the claim that it is outdated?
http://www.pythonocc.org/download/

**Comment by tpaviot** [comment]
https://github.com/tpaviot/pythonocc-core/releases/tag/0.16.5

**Comment by yoeldk** [comment]
With 0.16.5 it works fine in FF, issue can be closed.

Thanks,
Yoel
