### ISSUE TITLE
Edit HTML file before x3dom rendering

### ISSUE THREAD

**Issue by yoeldk** [tpaviot/pythonocc-core#285]
Hello,

Can I write code that will edit the HTML file that is being presented in the x3dom renderer?
(i.e add some text/menus).
If possible I would be happy if one can direct me to examples doing so.

Thanks,
Yoel

**Comment by tpaviot** [comment]
@yoeldk The HTML content is created by the module src/addons/Display/WebGl/x3dom_renderer.py

You just have to write your own renderer if ever the default HTML code is not enough.
