### ISSUE TITLE
GeomInt module is an empty SWIG module

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#293]
for instance, should contain the **GeomInt_SS** class, but basically empty

**Comment by tpaviot** [comment]
GeomInt module is empty in pythonocc-0.16.x versions, but it was recently added and should be available in the current master. Please @jf--- check. If ever it's ok with master, the issue can be closed.

**Comment by tpaviot** [comment]
I checked. GeomInt module is available in current master, as well as the GeomInt_IntSS class. I close the issue.

**Comment by jf---** [comment]
hi @tpaviot , sorry not being on the latest, I'll checkout & rebuild tomorrow. Sorry for the noise...
