### ISSUE TITLE
class BRepFeat_Builder don't inherits from BOPAlgo_BOP

### ISSUE THREAD

**Issue by chentao807** [tpaviot/pythonocc-core#297]
pythonocc-core version 0.16.5 (windows 64 bits)
In the file BRepFeat.py, class BRepFeat_Builde don't inherits from BOPAlgo_BOP

line 458: 

```python
class BRepFeat_Builder(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
```

**Comment by tpaviot** [comment]
@chentao807 Thanks for the report. It's already fixed in the current master, will be available in the next release.
