### ISSUE TITLE
Zoom in on a part of a model

### ISSUE THREAD

**Issue by lalvarezt** [tpaviot/pythonocc-core#298]
Hi,
I'm trying to zoom in on a part of a model, for that I have to calculate the projection of a given point in the 3D space on the screen, I tried using the camera in the View

`self.OCE_widget.display.View.Camera().ConvertWorld2View(gp_Pnt(xmin, ymin, zmin))`

But it says that the camera handle object doesn't contain the function ConvertWorld2View.

Am I doing something wrong, or there is another way to accomplish the same task.

Thanks

Edit: I solved my problem using 

`xpmin, ypmin = self.OCE_widget.display.View.Convert(xmin, ymin, zmin)`

But I would still like to access the Camera, how it could be done?

**Comment by jf---** [comment]
well, Shift + right mouse button does provide the functionality of zooming into an area, see the [ZoomArea](https://github.com/tpaviot/pythonocc-core/blob/master/src/addons/Display/OCCViewer.py#L527) method

or are you trying to zoom in on a selection in your viewer?

**Comment by lalvarezt** [comment]
sorry for the late reply and thanks for your answer, yes indeed the ZoomArea does provide the posibility that I want, also using WindowsFit. I translated the point coordinates to pixel coordinates and did the Zoom in. But i would like to access the camera to do transformations on it.

**Comment by jf---** [comment]
@lalvarezt, that's a coincidence, I share the need for being able to access the camera, I just reported #301 to do exactly that...

**Comment by jf---** [comment]
OCCT 7 supports this functionality

**Comment by tpaviot** [comment]
@lalvarezt The Camera object is available in pythonocc since the 0.18 release

@jf--- OCCT 6.9 already supports the ConvertWorld2View method, and is available in pythonocc

Committed an example related to 3d to 2d screen coordinates see 44e63d607a0f410f40f96ec03e46429ecb750823
