### ISSUE TITLE
Export SVG example is not working on Windows

### ISSUE THREAD

**Issue by johanesmikhael** [tpaviot/pythonocc-core#300]
I could not make the SVG export [example](https://github.com/tpaviot/pythonocc-core/blob/master/examples/core_display_export_to_EF.py) works in my Windows machine. It is said that the OCE/pythonocc should be built with gl2ps library to make it work. Fyi, I installed pythonocc from conda package.

**Comment by tpaviot** [comment]
Fixed in latest conda build for pythonocc-core 0.17.3
