### ISSUE TITLE
Module GEOMAlgo

### ISSUE THREAD

**Issue by jirihnidek** [tpaviot/pythonocc-core#303]
Hi,
was module `GEOMAlgo` removed or was it renamed? This blog post mentions `GEOMAlgo_Splitter`:

http://www.pythonocc.org/ecosystem/use-cases/pythonocc-and-smesh/

I would like to use it in my application. I tried to google it, but I didn't find any useful information.
Thanks.

**Comment by jf---** [comment]
hi @jirihnidek ,

Correct, the GEOM module ( from Salome ) isnt maintained currently.
Splitting shapes however is perfectly possible though, see the examples.
Let me know if you have a specific use case.

**Comment by tpaviot** [comment]
@jirihnidek I removed the outdated post from the blog. The GEOM addition to OCE/OCCT is not maintained anymore.

**Comment by jirihnidek** [comment]
hi @jf--- 

sorry for late response. I have specific use case. I can split one solid shape into the two solid shapes and glue them together using sewing:

![http://bacula.nti.tul.cz/~jiri.hnidek/pythonOCC-boolean01.png](http://bacula.nti.tul.cz/~jiri.hnidek/pythonOCC-boolean01.png)

but when I do meshing the the shape in GMSH, then meshing is compatible at lines, but it is not compatible at bordering face and it is problem

![http://bacula.nti.tul.cz/~jiri.hnidek/gmesh-meshing-boolean01.png](http://bacula.nti.tul.cz/~jiri.hnidek/gmesh-meshing-boolean01.png)

Thanks for advice.

**Comment by jf---** [comment]
its appears that when meshing the shape is not considered a TopoDS_Solid or TopoDS_Compound ,but rather 2 separate shells ( which don't require vertices to be shared on shared edges )

so I'm curious if the resulting file contains what kind of topology.
that would help answer the question whether GMSH can create a mesh with shared edges from compound or solid.

**Comment by trelau** [comment]
@jf--- @jirihnidek I implemented Salome 8.2.0 GEOMAlgo_Splitter and submitted a PR [here](https://github.com/tpaviot/pythonocc-core/pull/411).

**Comment by jirihnidek** [comment]
Hi, I solved the problem using boolean operations and reshaping. You can look at my progress in this issue : https://github.com/GeoMop/bapprox/issues/10#issuecomment-288761796. The source code can be found here: https://github.com/GeoMop/PythonOCC_Examples/blob/master/src/bspline_solid_boolean.py ... I'm not longer member of this project.

Cheers.

**Comment by jf---** [comment]
@jirihnidek ,  a PR on that example would be a welcome contrib! 
a very interesting project...

**Comment by tpaviot** [comment]
@jirihnidek I was not aware of the GeomMp project or the PythonOCC_Examples. There are many very interesting things, feel free to submit your examples so that they become part of pythonocc.

**Comment by jirihnidek** [comment]
Hi, @tpaviot . I'm no longer member of GeoMop project. I work at Red Hat since 1st April. I'm poking @janakolajaehlerova for submitting these examples :-). She needs to practice using git and github :-).

**Comment by jf---** [comment]
share @tpaviot feeling wrt to seeing many inspired examples, something of a gold mine ;)
