### ISSUE TITLE
Transparency Z order bug?

### ISSUE THREAD

**Issue by lalvarezt** [tpaviot/pythonocc-core#326]
Hi

![transparency bug](https://cloud.githubusercontent.com/assets/16566531/18882104/dfbb714e-84ab-11e6-8386-4d78650d9a98.png)

When I represent two transparent objects, one them is always in front of the other, it doesn't matter the angle of view. In the picture the red cylinder is in front of the green shape, but it gets represented on the back.

Also I'm getting the ragged edges on some shapes, even with antialising on.

Is this a pythonocc bug or OCE? Or is there a way to fix it?

Thanks in advance

**Comment by jf---** [comment]
good question, it would be easier to delve into this with an example that reproduces the problem. 
btw, the screenshot is looking good besides the transparency issue. can i ask how you managed to render the edges on top of the shaded geometry?

**Comment by jf---** [comment]
@lalvarezt , perhaps [this offers a clue](https://www.opencascade.com/doc/occt-6.9.0/refman/html/class_v3d___view.html): see **EnableDepthTest**

**Comment by jf---** [comment]
can reproduce with:


```python
def cut(event=None):
    # Create Box
    Box = BRepPrimAPI_MakeBox(200, 60, 60).Shape()
    # Create Sphere
    Sphere = BRepPrimAPI_MakeSphere(gp_Pnt(100, 20, 20), 80).Shape()
    # Cut: the shere is cut 'by' the box
    Cut = BRepAlgoAPI_Cut(Sphere, Box).Shape()
    display.EraseAll()
    ais_box = display.DisplayShape(Box)
    display.Context.SetTransparency(ais_box, 0.8)
    ais_cut = display.DisplayColoredShape(Cut, color="CYAN")
    display.Context
    display.Context.SetTransparency(ais_cut, 0.4)
    display.FitAll()
```

strange thing is that `display.View.IsDepthTestEnabled() -> True`

![image](https://cloud.githubusercontent.com/assets/620988/18885502/38571048-84ec-11e6-9847-edc6d1789b99.png)

**Comment by lalvarezt** [comment]
@jf--- Thanks for the reply, to render the edges on to of the shaded geometry use
`self.OCE_widget.context.DefaultDrawer().GetObject().SetFaceBoundaryDraw(True)`

**Comment by lalvarezt** [comment]
@jf--- So I guess, we'll have to wait for the new GLSL / raytracing. Thanks

**Comment by jf---** [comment]
@lalvarezt , it looks like it, though I agree that it looks shockingly aweful...

`self.OCE_widget.context.DefaultDrawer().GetObject().SetFaceBoundaryDraw(True)` 🍹 many thanks, an excellent find...

since we're on the topic, your screenshot ( yes, I read your post ) looks pretty good to me... have you done more trick wrt lighting & shading?

**Comment by tpaviot** [comment]
@lalvarezt  cant' reproduce the issue, either running oce-0.17 or 0.18. I added an example in commit 686ed9ac943f39f2f95d3ff6063473abdca5688b, can't see anything wrong. Can you please provide a test case

**Comment by tpaviot** [comment]
@lalvarezt ping
