### ISSUE TITLE
enable phong shading by default

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#328]
smoother hilights, performs interpolation of the normals where the vertices meet

![image](https://cloud.githubusercontent.com/assets/620988/18924405/615dcae4-85b0-11e6-99db-7058a347e017.png)

**Comment by tpaviot** [comment]
@jf--- can u submit a PR ?

**Comment by jf---** [comment]
Yes!

![image](https://cloud.githubusercontent.com/assets/620988/18930641/158cbabc-85c9-11e6-8150-f7cb4535243c.png)

**Comment by tpaviot** [comment]
Fixed by #330
