### ISSUE TITLE
enable rendering of contours on top of shaded geometry

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#329]
the edges make the topology a lot more understandable

thanks @lalvarezt for pointing this out...

![image](https://cloud.githubusercontent.com/assets/620988/18924361/38761ce4-85b0-11e6-8340-196587ee5650.png)

**Comment by tpaviot** [comment]
@jf--- can u submit a PR ?

**Comment by tpaviot** [comment]
Fixed by PR #330
