### ISSUE TITLE
change cursor on pan, rotate, zoom

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#335]
@tpaviot , PR follow soon

**Comment by tpaviot** [comment]
@jf--- which tag is this issue related to ? can please describe your expectations ?

**Comment by jf---** [comment]
when navigating the view, change the cursor to the navigational function used ( rotation, panning, zooming etc ). this makes things a lot more intuitive

**Comment by tpaviot** [comment]
@jf--- any progress regarding this issue ?
