### ISSUE TITLE
move examples to their corresponding directory

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#337]
@tpaviot we've spoken about this before, I think it would be cool to have all `core_geometry_*` examples in a `geometry` folder, which has a `README.md`. The advantage here is that we could have a folder of screenshots in the `pythonocc-core/doc/examples/_images/` folder. 

This way, when browsing Github, you're presented with a great looking gallery of what pythonocc is capable of.

Polish, true, but shiny is pretty 🍹

**Comment by tpaviot** [comment]
There's no need to move examples to different directories to generate screenshots and/or a readme.md The examples/screenshots and/or the readme.md should be automatically generated from the examples. 

Have a look at mrdoob threejs examples folder https://github.com/mrdoob/three.js/tree/dev/examples as well as the https://threejs.org/examples/ page. This is pretty good.

**Comment by jf---** [comment]
hi @tpaviot ,

wrt generated, that's obvious the right approach.
that said, we could think of a html gallery, with such an outline on the left, a code viewer next to it, with a webgl view next to that... i have a server that could run things

**Comment by jf---** [comment]
ok, perhaps its something to look into...
