### ISSUE TITLE
conda packaging solution has to be extended to support linux and windows

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-core#35]
In the conda REAME.md file, conda support is presented as a wip. In order to complete this work, 2 things are necessary:

* explain, in the documentation, how to use the yaml, build.sh and other files that are made available in the pythonocc-core source repository. Indeed, to *install* pythonocc-core on its own machine, only the REAME.md file is necessary. The documentation has to explain how to compile and upload new binaries to a shared location. This would allow users to contribute binaries ;

* so far, this work is osx specific. It has to be ported to linux and windows. Actually, this is on these platforms, and not osx, that distributing binaries is the more difficult.

I tag this issue as 0.16.0. If ever this is not possible to be achieved within this week, I will move the conda code to another branch, merged will be delayed to the 0.17.0 milestone.

**Comment by rainman110** [comment]
Hello everyone. I did some experimental packages for windows (win32). This is currently extremely wip.
Please have a look here: https://anaconda.org/DLR-SC/

**Comment by jf---** [comment]
hi @rainman110 , that's awesome!

Would you have a pointer to the conda.recipe?
It would be great to have this [integrated](https://github.com/tpaviot/pythonocc-contrib/tree/master/conda-pkg)

**Comment by rainman110** [comment]
Hi jelle, currently the repository for the recipes is not accessible from the outside, but I see no problem to share it with the community.

You can either extract the recipe from the conda package itself, or I could send you a zip file with our recipes.

Some important remarks:
  - I had to apply some patches on top of pythonocc-core, as multiple symbols weren't exported by oce
  - I had to change setting the environment variable CSF_GraphicShr in OCCViewer.py, as I don't place the OCE dlls not inside the Lib/site-packages/OCC folder, but in Library/bin. OCE is packaged as a separate conda package that installs its DLLs in that directory.

**Comment by jf---** [comment]
Many thanks for the pointers @rainman110 ...

Building pythonocc-core with its dependencies can prove to be a challenge, so being able to install it through conda will smoothen out quite a bit of friction...

ideally, I'd love to integrate this contribution through a pull request, but happiliy to integrate manually as well.

**Comment by rainman110** [comment]
@jf--- , I'd love to contribute it via pull request. I just need to now your packaging strategy. 
  - How do you handle the dependencies on os x?
  - Which packages do you provide as dependencies?
  - What about optional packages like FreeImage, Gl2ps, TBB ... ?
  - Where do you host the packages?
  - Do you include all deps in one package or do you provide separate packages?

In my current "implementation", I provide all dependencies as separate packages. Still everything can be installes with one single

     conda install pythonocc-core

**Comment by jf---** [comment]
Hi @rainman110 ,

@jf--- , I'd love to contribute it via pull request. I just need to now your packaging strategy.

> How do you handle the dependencies on os x?

you specify these in the meta.yaml file.
the cool thing is that conda will resolve the dependencies for you.

So pythonocc-core pretty much only utilizes the **cmake and OCE** as dependencies.

[I've added conda recipes for OCE, which perhaps answers your question?](https://github.com/tpaviot/pythonocc-contrib/commit/e29bda0b1bbccc1f0150013a7cce655c63e2f554)

> Which packages do you provide as dependencies?

So you can split up runtime / build requirements:

```yaml

requirements:
  build:
    - cmake
    - python
    - opencascade_community_edition
    - swig 2.0.10

  run:
    - python
    - opencascade_community_edition
```

> What about optional packages like FreeImage, Gl2ps, TBB ... ?

Ah, those are resolved when creating the OCE libs, let me attach these recipes at the end of the message. Added these to the **pythonocc-contrib** repo, [see this commit](https://github.com/tpaviot/pythonocc-contrib/commit/e29bda0b1bbccc1f0150013a7cce655c63e2f554)

So your question related to OCE rather than pythonocc-core.

> Where do you host the packages?

So after a succesful **conda build** compile you can automagically have the resulting binaries uploaded to anaconda. See [my page on anaconda here](https://anaconda.org/jf)

Conda utilized [**binstar**](http://docs.binstar.org/) for Continuous Integration and Continuous Delivery. Pretty powerful. 

> Do you include all deps in one package or do you provide separate packages?

Good question, yes, so that's what the OCE package is for.

> In my current "implementation", I provide all dependencies as separate packages. 

Definitely the way to go :8ball: 

> Still everything can be installes with one single

Lets not do that, creating a recipe per dependency is the way to go...

> Also, where do you have all the conda recipes?

Have I addressed that question here above?

**Comment by jf---** [comment]
@rainman110 , Since you've come this far, this is probably not needed, but both binstar & conda are pretty well documented:

[conda](http://conda.pydata.org/docs/building/recipe.html)

[binstar](http://docs.binstar.org/)

finally, a hugely valueble resource is [the conda-recipe repo](https://github.com/conda/conda-recipes), which has a huge nr of recipes...

last but not least, here's the [conda mailing list ( google groups )](https://groups.google.com/a/continuum.io/forum/#!forum/conda), its been really helpful & responsive for me.

**Comment by rainman110** [comment]
Hi @jf--- , I am sorry, but I probably asked my questions the wrong way. I am aware how the dependency management in conda works and how the build system/conda itself works. My questions were pyocc and oce specific. 

As you provided the OCE build recipe, many of my question are already answered now. Sill one question:

Were do you host the recipes for all the OCE dependencies (gl2ps, TBB, FreeImage) ? I have to build these as well for windows.

**Comment by tpaviot** [comment]
@rainman110 Have a look at https://github.com/QbProg/oce-win-bundle for oce dependencies on Windows. Thank you for this great contribution, conda package for pythonocc lacked a support for Windows. Not tested yet, I still need a couple of weeks before testing.

**Comment by rainman110** [comment]
@tpaviot, @jf--- I started building the dependencies for OCE. I have packages for
  - TBB
  - Gl2PS
  - FreeImage

Freetype is already in the conda repositories, so no need to build it. Currently, I made only win32 builds, but it should be easily adoptable to win64 as well.

We opened up our recipe repository, which is here: https://github.com/DLR-SC/tigl-conda
The binary conda packages can be downloaded here: https://anaconda.org/DLR-SC/

OCE is not yet been built against these dependencies. Currently, only freetype is included in the build. This will be changed, as soon I have some time for the compilation process.

@tpaviot I started testing our OCE builds. I built a python wrapper of our C++ library TiGL against pythonocc-core. So far, everything worked seemlessly - also the OpenGL based visualization.

**Comment by jf---** [comment]
hi @rainman110 , 

Wow, this is quite an accomplishment, congrats!
Thanks so much for sharing your work.

We now have a much better chance of building & distributing binaries of ( window / linux / osx ) for pythonocc, so this is a big stride fwd.

* I'm curious, I see quite a few edits in [the CMakeList patch](https://github.com/DLR-SC/tigl-conda/blob/master/python-occ/fixwindows.patch) you've created. Would you be so kind to comment on how these are an issue, such to have a better understanding of the patch. One of the patterns I'm curious of I've added here below. If you could comment on that, that would be a help. 


```diff
--- src/SWIG_files/wrapper/BRepBuilderAPI.i
+++ src/SWIG_files/wrapper/BRepBuilderAPI.i
@@ -734,14 +734,7 @@ class BRepBuilderAPI_VertexInspector : public NCollection_CellFilter_InspectorXY
 	:rtype: TColStd_ListOfInteger
 ") ResInd;
 		const TColStd_ListOfInteger & ResInd ();
-		%feature("compactdefaultargs") Inspect;
-		%feature("autodoc", "	* Implementation of inspection method
-
-	:param theTarget:
-	:type theTarget: int
-	:rtype: NCollection_CellFilter_Action
-") Inspect;
-		NCollection_CellFilter_Action Inspect (const Standard_Integer theTarget);
+
 };
```

* How shall we move further on the topic? Can I ask you to create a pull request ( for the pythonocc-contrib repo ) to continue the effort? 

Thanks again, this is exciting...

**Comment by jf---** [comment]
@rainman110 

I've installed on my windows VM, works out beautifully :trophy: 

![](https://www.dropbox.com/s/2ru3aloo8i3yscd/Screenshot%202015-12-02%2009.51.33.png?dl=1)

**Comment by rainman110** [comment]
@jf---  Nice to see, that everything is working.

> I'm curious, I see quite a few edits in the CMakeList patch you've created. Would you be so kind to comment on how these are an issue, such to have a better understanding of the patch. One of the patterns I'm curious of I've added here below. If you could comment on that, that would be a help. 

I admit, the patches are commented a bit sloppy, but these are necessary. Actually, the patch addresses 3 different problems:
 1. Fix a wrong install prefix. This is a bug in the CMakeLists.txt, which only affects windows. We should fix this in the repository.
 2. Fix not exported symbols: These are the many lines that you were citing. On Windows, you have to explicitly declare functions and methods, that should appear in the DLL. In OCE, this is done with the STANDARD_EXPORT macro. Some of the classes are missing this macro. Thus these methods are not available und therefor may not be wrapped. By removing the lines, I disable swig wrapping of the problematic methods.
 3. I am setting the CSF_GraphicShr to another directory, as the OCE DLLs aren't placed inside the site-packages/OCC directory, but in its own installation path.

> How shall we move further on the topic? Can I ask you to create a pull request ( for the pythonocc-contrib repo ) to continue the effort? 

I will clone the pythonocc-core repo as soon as I have time and make my changes. Then you'll get the pull request. Do you want me to apply and commit the patches 1+2 directly on the code or should we apply them during the build step only?

**Comment by jf---** [comment]
Hi @rainman110 

> @jf--- Nice to see that everything is working.

Seriously, to have pythonocc-core on a windows machine in < 5 minutes is a major achievement :trophy: :tropical_drink: 

> I will clone the pythonocc-core repo as soon as I have time and make my changes. Then you'll get the pull request. Do you want me to apply and commit the patches 1+2 directly on the code or should we apply them during the build step only?

1. the wrong prefix sounds conda specific? yes, so that's for the PR for pythonocc-contrib, where the conda recipes are currently located ( its a work in progress ) 
2. this seems a more fundamental issue, but I do feel out of my depth. @tpaviot , what is your take on the matter. This affects pythonocc-core.
3. I assume this is conda specific too?

Yes, so 1 + 3 -> a PR on pythonocc-contrib would be awesome, for 2 we probably should have Thomas Paviot's opinion on the matter, and affects the pythonocc-core repo.

Not sloppy at all, thanks for taking the time to explains the changes, that's hugely appreciated...

**Comment by rainman110** [comment]
Hi @jf--- 

 1. This is not conda specific, but a general pythonocc-core problem on windows.
 2. Also, windows problem.
 3. This is conda specific. Therefore it would make sense to use a patch instead of making a commit to the repo.

> Seriously, to have pythonocc-core on a windows machine in < 5 minutes is a major achievement :trophy: :tropical_drink:

Thanks for the flowers :smirk:

**Comment by jf---** [comment]
OK great, just so we're clear on what goes where ( 1 + 2 -> pythonocc-core / 3 -> pythonocc-contrib )

**Comment by rainman110** [comment]
> OK great, just so we're clear on what goes where ( 1 + 2 -> pythonocc-core / 3 -> pythonocc-contrib )

Absolutely correct!

**Comment by rainman110** [comment]
Now I also created the win64 packages. Should work out of the box.

I created a pull request for the windows fixes, waiting to be merged. Next, I will fix your recipies to be used on windows.

**Comment by rainman110** [comment]
I have built packages now for all major platforms (Linux, Mac, Windows). 
Conda packages: https://anaconda.org/dlr-sc/pythonocc-core
Conda recipes: https://github.com/DLR-SC/tigl-conda

Feel free to test. I will soon make a PR to your recipes to include windows and linux support.

**Comment by tpaviot** [comment]
@rainman110 That's pretty cool. Feel free to open a PR to pythonocc-contrib. With windows/linux support, conda package support will be considered as complete.

**Comment by jf---** [comment]
### Wooooohoooo!

---

This is absolutely amazing news :8ball: !!!
Yes, much look fwd to the PR...

Alright, I'll look into setting up  CI builds for the conda builds...
After that, it would be a good idea to poll our userbase to test the outcome.
If that's succesful, we could consider pointing to the conda binaries as the go-to install method.
@tpaviot , would that be the way to go about it?

Awesome, this is a great start of the day ;)
@rainman110 , this is awesome, I didn't have the skill & perseverance to pull this one off on all platforms, its an achievement. Look fwd to the PR...

-jelle

**Comment by waterbug** [comment]
Hi guys, just fyi:  I conda installed the linux package on my Ubuntu 14.04 box and from the few examples I tried it seems to work great, though I haven't had time to systematically test ... @rainman110 -- KUDOS!  This is a huge leap forward for pythonocc!  @tpaviot and @jf--- -- I'm very happy for you guys -- well done, keeping the fire!  :)  I hope to use pythonocc in a new app I'm just beginning (well, heh, really the latest incarnation of "pangalactic", if you remember(!)  ... more on that later. ;)  Cheers!
- Steve

**Comment by rainman110** [comment]
@jf--- Glad to hear that everyone seems to be happy and also that things seem to work :grinning: 

Platform independent development is my daily business, so for me it wasn't that hard to make the packages and I had to make them anyways for the users of our software.

Before I start with the pull request, all my other PRs need to be merged first. Else, I need to patch the code again, which I don't really want to do. The important PRs are:
 - #157 (Avoids wrapping non-exported methods + default parameter string fixes)
 - #158 (Incorrect build directory in CMakeLists.txt on windows)

**Comment by jf---** [comment]
hi Steve!

Awesome to hear from you, thanks for informing that pythonocc-core is in good shape ;) 
Happy to deduce that you think the conda / binstar builds are a big deal, I think so too...

pangalactic definitely stuck with me @waterbug , world dominance wouldn't cut it :sunglasses:

**Comment by jf---** [comment]
@rainman110 , @tpaviot I think we can close this issue...
