### ISSUE TITLE
2D graphics

### ISSUE THREAD

**Issue by kozintsev** [tpaviot/pythonocc-core#358]
Hello!

How to shown in the display 2D graphics: lines, splines, circles, etc?
Can I use the 2D graphics in 3D? To pull or rotate, thus building a the shape.
Is it possible?

Thanks!

**Comment by jf---** [comment]
hi @kozintsev , 

I think we can best point you to the [opencascade documentation](https://www.opencascade.com/doc/occt-6.8.0/overview/html/technical_overview.html)
