### ISSUE TITLE
Travis Issue libcurl-glic

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-core#361]
There might have been an update to travis workers. Indeed linux builds don't passa nymore because of a failure related to libcurl. See https://travis-ci.org/tpaviot/pythonocc-core/jobs/177998481

@rainman110 Did you change something to your curl build ?

**Comment by rainman110** [comment]
@tpaviot No, i have not changed anything to libcurl. If you look closely, you can see that the new job is using cmake 3.6 now. Before it was cmake 3.3.1 . The new cmake requires curl and installs it.

I suppose, i compiled curl on a too new gcc / glibc. I can try to fix this. As a workaround, force the old cmake 3.3.1.

**Comment by rainman110** [comment]
@tpaviot I changed now libcurl to require only glibc 2.14. So in theory, your workaround can be reverted now.

**Comment by tpaviot** [comment]
@rainman110 done, that works. Thank you for both the tip and the quick update
