### ISSUE TITLE
traitDisplay has no example

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-core#38]
an example is required in order to explain traitDisplay usage.

**Comment by jf---** [comment]
[enaml](https://github.com/nucleic/enaml) correctly implements the architecture of traitsui
I've done some research and its just amazing...
so closing this, and will contribute back a enaml replacement soon

@tpaviot : please close the issue -- no traitsui no more...

**Comment by tpaviot** [comment]
@jf--- enaml is very interesting, looking forward to your work!

**Comment by jf---** [comment]
Its shockingly simple in comparison to traitsui.
IMHO traitsui was the right idea with a *horrible* implementation
where enaml is the right idea with a **brilliant** implementation

here's a quick hack... 
the init driver event has *no* place in the .paintEvent method

a bit more work is needed, but perhaps fun to see...

```python
from atom.api import Typed
from atom.api import (set_default)
from enaml.qt import QtGui
from enaml.core.api import d_
from enaml.widgets.api import RawWidget, Window, Container
from OCC.Display.pyqt4Display import qtViewer3d


class OCCxxx(qtViewer3d):
    def __init__(self, parent):
        super(OCCxxx, self).__init__(parent)
        self._initialized = False

    def paintEvent(self, event):
        # Display can only be initialized when window is shown.
        # Showing windows etc is all magically done by traits
        # Initializing on the first paint event.
        # (resizeEvent and showEvent are too early)

        if not self._initialized:
            self.InitDriver()
            self.Test()
            self._initialized = True

        super(OCCxxx, self).paintEvent(event)


class OCCWidget(RawWidget):
    model = d_(Typed(OCCxxx))

    hug_width = set_default('weak')

    _initialized = False

    def create_widget(self, parent):
        canva = OCCxxx(parent)
        return canva

enamldef Main(Window):
    # event clicked
    Container:
        OCCWidget:
            hug_width = 'ignore'
            hug_height = 'ignore'

```

enaml-run this_snippet.enaml
