### ISSUE TITLE
Cannot set background color or image

### ISSUE THREAD

**Issue by dkaripidescp** [tpaviot/pythonocc-core#391]
Using the conda binaries, I've tried changing the background to a color or an image with the following script:
```
import time
from OCC.Display.SimpleGui import init_display
from OCC.Quantity import Quantity_NOC_BLACK

display, start_display, add_menu, add_function_to_menu = init_display()
display.SetBackgroundImage('black100x100.bmp')
display.Repaint()

time.sleep(2)

display.View.SetBackgroundImage('black100x100.bmp')   
display.Repaint()

time.sleep(2)

display.View.SetBackgroundColor(Quantity_NOC_BLACK)
display.Repaint()

input('Press Enter to exit.')
```
The file black100x100.bmp is a 100 by 100 image with every pixel black (0, 0, 0) in bmp format.

I also tried adding `display.Context.UpdateCurrentViewer()` in addition to the Repaint function calls. I did a number of searches and found other examples where the background color was changed.

Under none of the tests did the background ever change from the default gray gradient.

**Comment by tpaviot** [comment]
Commit 9db029e07fd62e5f89ff8af50e9b04dfcd1f7b03 adds an example.

![capture](https://cloud.githubusercontent.com/assets/660130/25521271/3d3dd050-2bff-11e7-9cdc-1172d3b8d89b.PNG)

@dkaripidescp This issue occurs if oce is not compiled with FreeImage support.
