### ISSUE TITLE
Salome GEOMAlgo_Splitter concept available

### ISSUE THREAD

**Issue by trelau** [tpaviot/pythonocc-core#410]
Just wanted to make this available in case you want to incorporate it into future releases...

The Salome GEOMAlgo_Splitter was always a useful tool in Salome so I migrated it to pythonocc as shown by [this commit](https://github.com/trelau/pythonocc-core/commit/30d71bc424aaacb5a39e50bba675fff0a37e8850).

The GEOMAlgo_Splitter header and source files are from Salome 8.2.0 release. The example below shows splitting two faces and an edge. You can use it by importing:

`from OCC.GEOMAlgo import GEOMAlgo_Splitter`

![capture](https://cloud.githubusercontent.com/assets/8950602/24575467/6b0b66f0-1674-11e7-957b-19793f0eaabd.JPG)

![capture2](https://cloud.githubusercontent.com/assets/8950602/24575468/6ce7d602-1674-11e7-9477-d092b73859ed.JPG)

**Comment by tpaviot** [comment]
@trelau interesting. Can you please create a PR ? (if you can add an example as well it would be cool)

**Comment by tpaviot** [comment]
Related PR is #411

**Comment by tpaviot** [comment]
Merged into master.
