### ISSUE TITLE
[Example] - ThreeJS WebViewer

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tpaviot/pythonocc-core#425]
Hello @tpaviot,

If you are interested, I can contribute the webviewer example I did for my project. 
Where do you want me to add it ?

It has been quite tricky to finally manage to import this JSON file, it might help someone one day.

For remind: https://github.com/DEKHTIARJonathan/dmu-net.org/tree/STEP-2-ThreeJS-BatchConverter/web

Have a great day,

Jonathan DEKHTIAR

**Comment by tpaviot** [comment]
@DEKHTIARJonathan The [pythonocc-contrib](https://github.com/tpaviot/pythonocc-contrib) repository seems to be the right place to contribute your web viewer. Just create a DMU-netWebViewer folder, at the same level than IFCViewer, WebServer etc. and create a PR. Thank you for your contribution.

**Comment by tpaviot** [comment]
@DEKHTIARJonathan what's the status of your proposal ? closing the issue, feel free to submit a PR to pythonocc-contrib
