### ISSUE TITLE
Install OCE/PYTHONOCC on Macosx

### ISSUE THREAD

**Issue by fperignon** [tpaviot/pythonocc-core#430]
Hi,

I tried to install oce + pythonocc on a Macosx 10.11.6.

The Install from source of oce 0.17.3 works fine but pythonocc 0.17.3 fails with:

Undefined symbols for architecture x86_64:  "TDataXtd_Axis::Set(TDF_Label const&)", referenced from:      _wrap_TDataXtd_Axis_Set__SWIG_0(_object*, int, _object**) in TDataXtdPYTHON_wrap.cxx.o

As a solution, I tried what is explained in my next comment
(which was supposed to be published, as this issue, on https://github.com/siconos/siconos/
 Sorry for the confusion)

**Comment by fperignon** [comment]
Solution : use conda.

- install anaconda using graphic installer (see https://docs.continuum.io/anaconda/install-macos.html)
- install python occ : 
conda create -n pythonocc -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core==0.17.3 python=3

- compile siconos (cxx-11 mode):
cmake ... -DCMAKE_CXX_STANDARD=11 -DSICONOS_USE_BOOST_FOR_CXX11=OFF 

Error :

Undefined symbols for architecture x86_64:
  "math_Vector::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const", referenced from:
      mymath_FunctionSetRoot::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in mymath_FunctionSetRoot.cxx.o
ld: symbol(s) not found for architecture x86_64


Problem comes from Dump function in 
/mechanics/src/mechanisms/CADMBTB/mymath_FunctionSetRoot.cxx 
used to overload ostream op.

Found something here:
https://www.opencascade.com/content/problems-getting-output-file-dump-method

Any idea of a proper solution?

**Comment by tpaviot** [comment]
@fperignon I have no idea about what's wrong. Is Osx 10.11.6 the latest available version ? I used to work on a MacbookPro some years ago, but I don't have any osx machine anymore. The conda binaries are compiled using the travis-ci osx virtual machine, I can't drive any additionnal test.

Can you please run the unittests that come with pythonocc ?

**Comment by rainman110** [comment]
@fperignon @tpaviot The pythonocc packages are compiled with MACOSX_DEPLOYMENT_TARGET=10.8.

This means, that no C++11 is available and the libstdc++ is beeing used by OCE. When you compile siconos, it will probably use libc++ with C++11 support. Hence, you'll get linker errors.

When you want to link against the conda packages, you have to use MACOSX_DEPLOYMENT_TARGET=10.8 and disable C++11.

**Comment by tpaviot** [comment]
The latest master branch (future pythonocc-0.18.1) uses MACOSX_DEPLOYMENT_TARGET=10.9, and is linked against libc++
