### ISSUE TITLE
get_backend function not found

### ISSUE THREAD

**Issue by kozintsev** [tpaviot/pythonocc-core#438]
Hello!
I watched python-occ examples and in...
_pythonocc-core/examples/core_visualization_overpaint_viewer.py line 41-43_
get_backend function not found

Yours faithfully!

**Comment by chavan-vjti** [comment]
Same error on my side 👎 
any solution to his issue?

**Comment by kozintsev** [comment]
@chavan-vjti look here:
https://github.com/kozintsev/ResearchPythonOCC/blob/master/InteractiveEditor/TestQtBackendNative.py

Maybe it will help you.

**Comment by chavan-vjti** [comment]
@kozintsev 
Thank you for your help.
I'll let you about this.
Thank you!

**Comment by chavan-vjti** [comment]
@kozintsev 
I tried the above mentioned python program that you suggested but nothing gets displayed in the Python OCC screen. It remains blank even though we've mentioned the command as, "print('hello')".
Any reason ?

**Comment by tpaviot** [comment]
@kozintsev fixed by PR #447 Thanks for your report.
