### ISSUE TITLE
 Where is function BRepMesh::Mesh()

### ISSUE THREAD

**Issue by qqnzhyxxx** [tpaviot/pythonocc-core#442]
in C++ , we can use 
` BRepMesh::Mesh(face, deflection);  `
`Handle_Poly_Triangulation triFace = BRep_Tool::Triangulation(face, location); `
 But where is the function  BRepMesh::Mesh()  in pythonocc?

Thanks for you Reading, and Waiting for relply.

**Comment by rainman110** [comment]
It is now called ```BRepMesh_IncrementalMesh```.

**Comment by qqnzhyxxx** [comment]
Oh, I see！ Thanks for your reply.
