### ISSUE TITLE
_qApp is set to None in the constructor of qtViewer3d

### ISSUE THREAD

**Issue by adam-urbanczyk** [tpaviot/pythonocc-core#451]
_qApp is set to None in the constructor of qtViewer3d:

https://github.com/tpaviot/pythonocc-core/blob/d90e0c3fb17a0dbe3beb8ad6cd46d9516032f290/src/Display/qtDisplay.py

and when later referenced causes an unhandled exception (at least under PyQt5).

https://github.com/tpaviot/pythonocc-core/blob/d90e0c3fb17a0dbe3beb8ad6cd46d9516032f290/src/Display/qtDisplay.py#L271

 If you agree with this issue I'll make a PR.

**Comment by tpaviot** [comment]
@adam-urbanczyk ok, please submit a PR

**Comment by tpaviot** [comment]
Fixed by #453
