### ISSUE TITLE
How to use Geom_BSplineSurface

### ISSUE THREAD

**Issue by tnakaicode** [tpaviot/pythonocc-core#472]
I ran BSpline.py and got error following.

"RuntimeError: Standard_ConstructionError
Geom_BSplineSurface"

I don't know the cause of this error. Please tell me how to use Geom_BsplineSurface.

[BSpline.zip](https://github.com/tpaviot/pythonocc-core/files/1520740/BSpline.zip)

**Comment by tpaviot** [comment]
@tnakaicode Please copy/paste python code in the issue tracker rather than a zip file

**Comment by tpaviot** [comment]
Following resources about how to use Geom_BSpline_Surface:

* https://www.opencascade.com/doc/occt-6.9.1/refman/html/class_geom___b_spline_surface.html

* https://cdn.rawgit.com/tpaviot/pythonocc-core/e05ec51b/doc/apidoc/0.18/OCC.Geom.html?highlight=geom_bsplinesurface#OCC.Geom.Geom_BSplineSurface

* https://github.com/tpaviot/pythonocc-core/blob/master/examples/core_topology_face.py
