### ISSUE TITLE
Display issue with wx backend on Linux

### ISSUE THREAD

**Issue by guillaume-florent** [tpaviot/pythonocc-core#476]
The 3D viewer from OCC 17.3 with a wx backend does not work on Linux: the viewer uses the GetHandle() method from wxWindow that always returns 0 on Linux for versions > 2.8 of wxPython (that's a known bug/limitation of wx that has already been met by other projects using wx).

**Comment by guillaume-florent** [comment]
A correction is suggested at https://github.com/cztomczak/cefpython/issues/349

**Comment by guillaume-florent** [comment]
Commit 00a375ae093bafedbaced611f1a684eacbffc289 solves the problem by waiting 2 seconds from the frame to get its handle ready.

**Comment by tpaviot** [comment]
Here 5b9d1f468ef8a1e011e342d5b82fa4ffbf40a462 a better implementation, moved to wxDisplay rather than SimpleGui

**Comment by tpaviot** [comment]
Fixed.
