### ISSUE TITLE
Standard_OutOfRange

### ISSUE THREAD

**Issue by FullStackRafik** [tpaviot/pythonocc-core#489]
Hi,
I get the following error when reading AP238 file:
Failed to read the file: Standard_OutOfRange.
Can you please tell me if there is any solution for that.

Thanks

**Comment by tpaviot** [comment]
AP238 is not supported. Only AP203 and 214.

**Comment by FullStackRafik** [comment]
Hey tpaviot,
Thanks for your reply.
Is there any solution for that? or any other library that can support AP238?
Thanks

**Comment by tpaviot** [comment]
Try stepcode https://github.com/stepcode/stepcode

**Comment by FullStackRafik** [comment]
Thanks again, I'll try to use it.
Is there any support for python in this library?

**Comment by tpaviot** [comment]
Using stepcode, you can parse an EXPRESS file and generate a python module, then it's possible to load/write files accordingly. I wrote the first version of this exporter, years ago, I don't know the current status.

**Comment by FullStackRafik** [comment]
Thanks for your reply.
I know how to use the parser to generate python from express, but I need to know how to display the 3D view of AP238.
