### ISSUE TITLE
brepgprop_LinearProperties crashes

### ISSUE THREAD

**Issue by seeul8er** [tpaviot/pythonocc-core#491]
I try to get the length of an TopoDS_Edge or TopoDS_Wire using:
```python
props = GProp_GProps()
brepgprop_LinearProperties(_wire, props)
print(props.Mass())
```
Where `_wire` is a `TopoDS_Wire`.
The code/programm crashes with: `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

Background:
I imported a file as .stp and got the edges etc. 
Tested it with a .stl import: No crashes so far. Is it a bug or am I doing something wrong?
The code seems to crash on `brepgprop_LinearProperties()`
Used `pythonocc-core 0.18.1`

Amazing project btw.! :+1:

**Comment by tpaviot** [comment]
can you please provide a test case. Hard to debug without any additional material

**Comment by tpaviot** [comment]
Try with the latest version, if ever it still fails reopen the ticket

```
conda create --name=whatever-name python=3.7
source activate whatever-name
conda install -c dlr-sc -c pythonocc pythonocc-core=7.4.0beta2
```
