### ISSUE TITLE
Jupyter Notebook- NameError: name 'MeshPhongMaterial' is not defined

### ISSUE THREAD

**Issue by a-parida12** [tpaviot/pythonocc-core#498]
I am trying out the hello world Jupyter Notebook example.
When I try to import the **JupyterRenderer**
by using
`from OCC.Display.WebGl.jupyter_renderer import JupyterRenderer`
I get a NameError:
`NameError: name 'MeshPhongMaterial' is not defined`

**Comment by tpaviot** [comment]
You need the latest pythreejs development version. Go and check https://github.com/jovyan/pythreejs, checkout and install from sources.
