### ISSUE TITLE
GLSL example: missing class Graphic3d_ShaderProgram_Handle 

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#5]
I've created a branch to experiment with GLSL shaders.
There is a complete example, that is not functional due to a missing `Graphic3d_ShaderProgram_Handle`. 

See: jf---@SHA ref: ee26375c1f465a80003477403fde80a278b36624

( mehhh, cannot assign a pre-announce label ;( )

**Comment by jf---** [comment]
here's a WIP example to utilize shaders ( yeah! ) in pythonocc.
see ``>>>`` where the program fails ( attaching the shader )


```python
##Copyright 2010-2016 Jelle Feringa (jelleferinga@gmail.com)
##
##This file is part of pythonOCC.
##
##pythonOCC is free software: you can redistribute it and/or modify
##it under the terms of the GNU Lesser General Public License as published by
##the Free Software Foundation, either version 3 of the License, or
##(at your option) any later version.
##
##pythonOCC is distributed in the hope that it will be useful,
##but WITHOUT ANY WARRANTY; without even the implied warranty of
##MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##GNU Lesser General Public License for more details.
##
##You should have received a copy of the GNU Lesser General Public License
##along with pythonOCC.  If not, see <http://www.gnu.org/licenses/>.

#-------------------------------------------------------------------------------
# Example for attaching GLSL shaders to shapes
# GLSL stands for OpenGL Shader Language
# Find out more about GLSL here: http://www.lighthouse3d.com/opengl/glsl/
#-------------------------------------------------------------------------------

import os, glob
from OCC.Display.SimpleGui import init_display
from OCC.BRepPrimAPI import BRepPrimAPI_MakeSphere
from OCC.Graphic3d import (Graphic3d_ShaderProgram, Graphic3d_TOS_VERTEX, Graphic3d_TOS_FRAGMENT,
                           Graphic3d_ShaderObject)
from OCC.TCollection import TCollection_AsciiString

display, start_display, add_menu, add_function_to_menu = init_display()
my_box = BRepPrimAPI_MakeSphere(20.).Shape()

# render the sphere with default shading attributes ( no GLSL shader attached! )
anIO = display.DisplayShape(my_box, update=True)

# returns the directory where OCE stores the GLSL shaders
_shader_dir = Graphic3d_ShaderProgram.ShadersFolder()
# convert the returned TCollection_AsciiString to a python string
shader_dir = "".join([_shader_dir.Value(x+1) for x in range(_shader_dir.Length())])

# look for the shaders stored in the shader folder...
# only a single vertex (vs) and fragment (fs) shader for the moment
_phong_vs = glob.glob(os.path.join(shader_dir, "*.vs"))[0] # PhongShading.vs
_phong_fs = glob.glob(os.path.join(shader_dir, "*.fs"))[0] # PhongShading.fs

# construct TCollection_AsciiString from string
phong_fs = TCollection_AsciiString(_phong_fs)
phong_vs = TCollection_AsciiString(_phong_vs)

# construct the shader, load, compile and attach the GLSL programs
aProgram = Graphic3d_ShaderProgram()
aProgram.AttachShader(Graphic3d_ShaderObject.CreateFromFile(Graphic3d_TOS_FRAGMENT, phong_fs ) )
aProgram.AttachShader(Graphic3d_ShaderObject.CreateFromFile(Graphic3d_TOS_VERTEX, phong_vs ) )

# attach the shader to the AIS_Shape representation that renders the sphere
aspect = anIO.GetObject().Attributes().GetObject().ShadingAspect().GetObject().aspect().GetObject()
# h_aProgram = aspect.ShaderProgram() # returns a Graphic3d_ShaderProgram_Handle
#-------------------------------------------------------------------------------
# h_aProgram -> Graphic3d_ShaderProgram_Handle cannot be cast to a Graphic3d_ShaderProgram
# aProgram has not method .GetHandle...
# aspect.SetShader requires a `Graphic3d_ShaderProgram_Handle` instance
#-------------------------------------------------------------------------------
sm = display.Context.MainPrsMgr().GetObject().StructureManager()
global_shader = sm.GetObject().FillArea3dAspect().GetObject().ShaderProgram()

# attach to a single shape

>>> the next line is at fault...

aspect.SetShaderProgram(aProgram.GetHandle())

# update the rendering attributes such that the sphere is rendered with the GLSL shader
display.Context.Redisplay(anIO)
# type(aspect.ShaderProgram())
# Out[76]: SwigPyObject

# start the GUI event loop
start_display()
```

**Comment by tpaviot** [comment]
Some handles of Graphic3d are defined in a way that is not consitent with the rest of the API. Actually oce handles are defined in hxx headers with the name Handle_SomeClass.hxx, whereas Graphic3sd defines some Graphic3dClass_Handle.hxx. I modified the wrapper generator and pushed the updated Graphic3d.i see commit 4ed65ec75a7300be7edc514abd9ceba2e7b1b221

**Comment by tpaviot** [comment]
Fixed by commit 4ed65ec

**Comment by jf---** [comment]
hi @tpaviot ,

So its pretty cool the options by which you can customize the OpenGL pipeline.
I managed to get the GLSL shaders to work by setting 
``  aDriver->ChangeOptions().ffpEnable = Standard_False;``
this enables modern OpenGL, and should be our default ( faster as well... )

``aDriver->ChangeOptions().glslWarnings = Standard_True;``
is also useful; warning you when something is wrong with your shaders.
for instance, it seems nessecary to load ``DeclarationsImpl.glsl`` before using the OCC shaders.
you're gonna have a hard time finding that out without having this flag set.

``  aDriver->ChangeOptions().buffersNoSwap = Standard_False;``
is needed when overpainting in QML ( I've got a QML example up and running, where there is a HUD gui defined... yeaah :tropical_drink:  )

Display3d.cpp
```c++
    Handle(OpenGl_GraphicDriver) aDriver = Handle(OpenGl_GraphicDriver)::DownCast (myV3dViewer->Driver());
  // Enables FFP (fixed-function pipeline), do not use built-in GLSL programs
  // (ON by default on desktop OpenGL and OFF on OpenGL ES)
  aDriver->ChangeOptions().ffpEnable = Standard_False;
// required when overpainting in Qt5 / QML
  aDriver->ChangeOptions().buffersNoSwap = Standard_False;
  // Print GLSL program compilation/linkage warnings, if any...
  //aDriver->ChangeOptions().glslWarnings = Standard_True;
```

**Comment by tpaviot** [comment]
@jf--- Happy you succeeded with experimenting GSL, it took time but we got it. These OpengL options are really interesting, actually I never really looked at them. Rather than making the default as you say, we can extend the display3d class with some methods that can enable/disable those flags (in the same way occt did with the common/view.cxx file). Let keep the current config as the default (it uses to work on most machines, except intel drivers), and let the advanced user tune his opengl config according to his needs.

**Comment by tpaviot** [comment]
@jf--- can you please create a PR with the shader files/the python script and your modif to display3d.cpp so that we can test ?

**Comment by tpaviot** [comment]
On my machine, it compiles/runs but i can' see any shader applied.

**Comment by jf---** [comment]
hi Thomas, 

so i manipulated the light source in the Phong shader to see some first result.
this confirms that technically things are in working order.
i couldnt get the pink shaders in your webgl example to work ( though that seems a good idea ) 

yes, I'll do a PR for a first version of this.
thanks for your input...
