### ISSUE TITLE
question about performances

### ISSUE THREAD

**Issue by avigliotti** [tpaviot/pythonocc-core#501]
Hi,

first of all thanks for the great work and for sharing it!

I am a newbie with pythonocc and rather a newbie with python in general, and I would like to use it for generating large repetitive lattice structures ,
I wondering whether I'm doing anything wrong, or there is any way I can improve the performances of my script,

the code I am pasting below generates 32 hexagonal cells, and it takes on my computer, 20 sec. to produce the single shapes, and about 3 minutes, for fusing them together (needed to generate a stl. suitable for 3D printing), with the time increasing exponentially with the number of hexagons, taking a few hours to produce a few hundreds of hexagons, but I would like to produce structures with a few tens of thousands of cells in three dimensions as fast as possible to be able to optimize the positions of the nodes etc, 

may be this is not even the right place to ask, but any help or advice will be greatly appreciated

mt script is here: [https://github.com/avigliotti/tmp_pythonocc_test/blob/master/test_make_Hexa_lattice.ipynb](url)

many thanks,
andrea

**Comment by Achim66** [comment]
Hi,
you should avoid as much fusing operations as possible.
You can try this code:
[test_make_Hexa_lattice_1.zip](https://github.com/tpaviot/pythonocc-core/files/1681709/test_make_Hexa_lattice_1.zip)
