### ISSUE TITLE
Misaligned elements in STEP-import

### ISSUE THREAD

**Issue by Schnierle** [tpaviot/pythonocc-core#511]
Good morning pythonocc-community,

I am experiencing problems with the import of some step-Files with pythonocc 0.18.1, Win10.
You can test the behaviour with this File: [turbine_stp.zip](https://github.com/tpaviot/pythonocc-core/files/1726865/turbine_stp.zip)

My test import results:

**Autodesk Inventor 2018 Professional:**
![inventor_turbine](https://user-images.githubusercontent.com/36483773/36247310-dc3b87f4-1233-11e8-9f10-b606e7ecf080.png)

**FreeCAD-0.16.6712:**
![freecad_turbine](https://user-images.githubusercontent.com/36483773/36247394-32c1b5ee-1234-11e8-9be9-e41634d9169a.png)

**Pythonocc 0.18.1 Import with core_load_step_with_colors.py**
![pythonocc_turbine_hint](https://user-images.githubusercontent.com/36483773/36247493-88b68aec-1234-11e8-8b51-367ba7754b77.jpg)

As you can see, there are some misaligned elements in the pythonocc import (highlighted with blue color). I imported the step-File with core_load_step_with_colors.py from the examples-folder.

Can you reproduce this behaviour? Are there any hints on solving this?

Thanks and best regards
Marc

**Comment by tpaviot** [comment]
Thanks for the report, I'll check what's wrong

**Comment by Schnierle** [comment]
Thank you very much for your fast reply! 
I have carried out some research and tried to isolate the behavior. It looks like a problem with the drill holes.

[turbine_housing.zip](https://github.com/tpaviot/pythonocc-core/files/1727179/turbine_housing.zip)
**Pythonocc 0.18.1**
![pythonocc_turbine_2](https://user-images.githubusercontent.com/36483773/36251212-aa0cd104-1240-11e8-994c-48d895bef6b1.png)

Another example file: [rotary_table.zip](https://github.com/tpaviot/pythonocc-core/files/1727216/rotary_table.zip)

**Pythonocc 0.18.1**
![rotary_table](https://user-images.githubusercontent.com/36483773/36251754-a293d6d2-1242-11e8-81d6-b29c5c12aac6.png)

Interesting point: When I create a cube in Autodesk Inventor and drill a hole into it, we get correct results
 in pythonocc.
See this file: [cube.zip](https://github.com/tpaviot/pythonocc-core/files/1727267/cube.zip)

**Pythonocc 0.18.1**
![cube](https://user-images.githubusercontent.com/36483773/36252225-1fe259d2-1244-11e8-81ad-a6792b413762.png)

Greetings
Marc

**Comment by Schnierle** [comment]
Good evening Thomas @tpaviot,

I'm still interested in a solution for the described issue. Did you find anything on this issue or a hint for further research I could do?

Thanks and keep up the great work
Marc

**Comment by d-zimmermann** [comment]
Same Issing also here https://github.com/tpaviot/pythonocc-demos/issues/5

**Comment by tpaviot** [comment]
Fixed by PR #615 
![capture du 2019-01-13 09-08-33](https://user-images.githubusercontent.com/660130/51083029-0360be00-1713-11e9-8557-59f7ad9ab2d1.png)
![capture du 2019-01-13 09-11-22](https://user-images.githubusercontent.com/660130/51083044-3b680100-1713-11e9-83a1-ed8dd12c89e6.png)
