### ISSUE TITLE
wx backend in SimpleGUI not working

### ISSUE THREAD

**Issue by Durksz** [tpaviot/pythonocc-core#542]
I'm trying to use the simpleGUI with the wx backend but found it to be not working. 

Using Python 3.6 and PythonOCC 0.18.1

the error that appears is the following:
""
display, start_display, add_menu, add_function_to_menu = init_display(backend_str="wx",size=(1000,5000))
File "C:\ProgramData\Anaconda3\lib\site-packages\OCC\Display\SimpleGui.py", line 82, in init_display
    from wxDisplay import wxViewer3d

ModuleNotFoundError: No module named 'wxDisplay'
""
I found it can be solved quite easily by replacing line 77 "from wxDisplay import wxViewer3d" by "from OCC.Display.wxDisplay import wxViewer3d"

**Comment by tpaviot** [comment]
Confirmed. Fixed by commit 72b32e46 thanks.
