### ISSUE TITLE
Display Problems

### ISSUE THREAD

**Issue by NicoPauen** [tpaviot/pythonocc-core#543]
I am trying to work with pythonOCC in combination with IFCOpenShell to analyze IFC-Files regarding amounts of DIN 276. Therefore have to stick with Version 17.3 of PythonOCC, because the latest release of IFCOpenShell requires OCE 17.3. I will work on writing the needed IFCOpenShell Code by myself in the future to be able to update to pythonOCC 18.3. If there are any other workarounds to get the newest release of PythonOCC while sticking to the old IFCOpenShell, I would be happy to learn about them.  I am working with anaconda on a Mac.

When I start a display, either with ifcopenshell or directly through pythonOCC, I have this problem:

<img width="1108" alt="bildschirmfoto 2018-07-11 um 18 53 17" src="https://user-images.githubusercontent.com/37868872/42587670-bd53cd3a-853b-11e8-99b0-22ce0a279e22.png">

Code:

occ_display = ifcopenshell.geom.utils.initialize_display()
....
occ_display.FitAll()
ifcopenshell.geom.utils.main_loop()  

I am not able to get the frame to the complete size. And when I am displaying elements and move the mouse over the dark grey part, they get selected where they should have been if the windows would fit the whole screen.

**Comment by tpaviot** [comment]
You should compile the latest ifcopenshell master branch, previous precompiled package are outdated
