### ISSUE TITLE
Install issue 

### ISSUE THREAD

**Issue by esmaascioglu** [tpaviot/pythonocc-core#548]
my code gives error while trying to install. I am using python 3.5, win64. 
conda install -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core=0.18.0 python=3.5

The error is ,

UnsatisfiableError: The following specifications were found to be in conflict:
  - ifcopenshell -> python[version='>=3.6,<3.7.0a0']
  - python=3.5
Use "conda info <package>" to see the dependencies for each package.

**Comment by tpaviot** [comment]
If you want to run both pythonocc and ifcopenshell together, it's better to do the compilation by your own. The last ifcopenshell relase/conda package is quite old.
