### ISSUE TITLE
Issue on OCC.IFSelect module

### ISSUE THREAD

**Issue by cityofstaaars** [tpaviot/pythonocc-core#549]
hello.

I'd like to know what function is available if I import IFSelect_RetDone and IFSelect_ItemsByEntity class from OCC.IFSelect module.

There is no description about those classes in module index page of pythonocc.org .

thank you

**Comment by tpaviot** [comment]
See the official opencascade documentation https://www.opencascade.com/doc/occt-6.9.0/refman/html/_i_f_select___return_status_8hxx.html and https://www.opencascade.com/doc/occt-6.9.1/refman/html/_i_f_select___print_count_8hxx.html
