### ISSUE TITLE
unify examples & unit test

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#55]
i think it could be a great :gem: idea if we can unify our examples & unit tests

for instance, for the STL example that I just PR'd... 
why not a unittest that imports from the example file ( should be a func here ) and runs and validates that an STL file has been exported.

would you consider this a meaningful extension of the test suite?
I recall how in the good ol' days that we took time to wade through the examples before a release.

since we're now on the idea of master == release, i think it actually could make sense

**Comment by tpaviot** [comment]
Both don't have the same purpose. Examples aim at showing people how to use pythonocc. I'm not even sure they should be considered as functional tests (to be automated with Cucumber for instance). But, of course, we have to take care that all examples run before a release.
