### ISSUE TITLE
Boolean operation using pythonOCC and IfcOpenShell

### ISSUE THREAD

**Issue by apwbd7** [tpaviot/pythonocc-core#556]
Hi!

I tried doing the following Boolean CUT operation using shapes of IfcDoor and IfcWall instances:

Case 1.:
`settings = ifcopenshell.geom.settings()`
`settings.set(settings.USE_PYTHON_OPENCASCADE, True)`
`mold = OCC.BRepAlgoAPI.BRepAlgoAPI_Cut(mold, ifcopenshell.geom.create_shape(settings, ifc_file.by_type("IfcDoor")[0]).geometry).Shape()`

Case 2.:
`settings = ifcopenshell.geom.settings()`
`settings.set(settings.USE_PYTHON_OPENCASCADE, True)`
`mold = OCC.BRepAlgoAPI.BRepAlgoAPI_Cut(mold, ifcopenshell.geom.create_shape(settings, ifc_file.by_type("IfcWall")[0]).geometry).Shape()`

here mold is just a big box shape created using OCC.BRepPrimAPI.BRepPrimAPI_MakeBox

The trouble is: while in the case of an IfcWall instance, the CUT operation is successful; for IfcDoor, it gets stuck and my display window just freezes forever. I don't know why this happens.. maybe it has something to do with what IfcOpenShell returns in ifcopenshell.geom.create_shape(settings, ifc_file.by_type("IfcDoor")[0]).geometry that makes it difficult for pythonOCC to work with?

Can someone shed some light in this, please? thank you :)

**Comment by tpaviot** [comment]
Impossible to help without any further information. Closing the. Please @apwbd7 reopen if necessary, providing new material to help debugging.
