### ISSUE TITLE
TopoDS_Shape from a pointer?

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#56]
Would it be possible for pythonocc to get a TopoDS_Shape from a pointer?
This would encourage experimentation from other OCE related projects.

I do realize this would open the gate for segfault hell probably :hear_no_evil:

**Comment by tpaviot** [comment]
@jf--- Here is a blogpost for working with both ifcopenshell/pythonocc http://blog.ifcopenshell.org/2014/12/combining-ifcopenshell-and-pythonocc.html

**Comment by jf---** [comment]
Yeah, really cool right... 
So the thing is that moving TopoDS_Shape from ifcopenshell -> pythonocc is handled by serializing them. I'm kind of curious if we can create those instances from a pointer?

I guess the underlying question really comes down to how one extends the pythonocc wrappers.
That would be the right way to bind these projects closer together, since ifcopenshell effectively is generating SWIG wrapper code for exactly the same entities. That creates fragmentation and a friction while I think these projects should work hand in hand.
