### ISSUE TITLE
How to get current model's handle?

### ISSUE THREAD

**Issue by dongpipi** [tpaviot/pythonocc-core#589]
Hello:
I just started learning pythonocc for a few days
And have a question that how i can get the model's/shape's handle 
For example, I imported a cylinder .stp file and open/display it in the window, now how can I get the handle of the cylinder?
If more than 1 model, how to get them all？
Thank you very much!

**Comment by zhaowei699** [comment]
I also want to know it.

**Comment by liuxin2322** [comment]
i will use two-language to explain it 我会使用两种语言去解释
you can try follwing code你可以尝试下面的代码
···
‘’‘skip import （import部分不写了）’‘’
def recognize_clicked(shp, *kwargs):     #
    """ This is the function called every time
    a face is clicked in the 3d view  该函数可以使得面被选中
    """
    for shape in shp: #select topods_face 选中一个面
        face = topods_Face(shape)
        Umin, Umax, Vmin, Vmax = breptools_UVBounds(face1) #get uvbound 获得uv范围
        print(Umin, Umax, Vmin, Vmax)

if __name__ == '__main__':
    display, start_display, add_menu, add_function_to_menu = init_display()
    display.SetSelectionModeFace()  # switch to Face selection mode,启动面的选中功能
                                                        # display.SetSelectionModeVertex() 启动点的选中功能
    display.register_select_callback(recognize_clicked)   #点击执行某功能
    start_display()
···
