### ISSUE TITLE
can not create QPainter in QGLWidget(qtViewer3d)

### ISSUE THREAD

**Issue by zhaowei699** [tpaviot/pythonocc-core#592]
when I pressed "shift" to paint a rect by qtViewer3d of qtDisplay.py, but script will be crashed.
`        if self._drawbox:`
 `    `    `       self.makeCurrent()`
`       `    `       print("Start to create Qpainter")`
`       `    `       painter = QtGui.QPainter(self)`
`         `    `     painter.setPen(QtGui.QPen(QtGui.QColor(0, 0, 0), 1))`
`      `    `        rect = QtCore.QRect(*self._drawbox)`
`      `    `        painter.drawRect(rect)`
`       `    `       painter.end()`
`       `    `      self.doneCurrent()`

the error message:
QWindowsGLContext::makeCurrent: SetPixelFormat() failed (The pixel format is invalid.)
QWindowsGLContext::makeCurrent: SetPixelFormat() failed (The pixel format is invalid.)
QWindowsGLContext::swapBuffers: Cannot find window 0xf0e0e
QWindowsGLContext::swapBuffers: Cannot find window 0xf0e0e
INFO:OCC.Display.qtDisplay: key : 16777248
not mapped to any function
QWindowsGLContext::swapBuffers: Cannot find window 0xf0e0e
QWindowsGLContext::makeCurrent: SetPixelFormat() failed (The pixel format is invalid.)
Start to create Qpainter
QWindowsGLContext::makeCurrent: SetPixelFormat() failed (The pixel format is invalid.)

**Comment by zhaowei699** [comment]
I think it is a bug, but no people feedback to me. maybe I am not saying clearly. please kindly see the follow code.
`from OCC.Display.qtDisplay import qtViewer3d` 
then create a widget by qtViewer3d
`self.canva = qtViewer3d(self)`
when I run the script, everything looks good. It is no problem to move, scale, rotate model and so on. but if you press the key "Shift" and drag the rectangle by mouse(left or right button) to select some objects in this widget, the script will be crashed. If you only use mouse to click, it is ok to select the single  object.
summary: **when you press "Shift" and drag the rectangle by mouse, the script will be crashed.**

**Comment by tpaviot** [comment]
Fixed in current master branch.
