### ISSUE TITLE
how to use BRepLProp_SurfaceTool?

### ISSUE THREAD

**Issue by liuxin2322** [tpaviot/pythonocc-core#593]
after reading iges file and selecting surface, i want to compute the specific point information(coordinate and normal) on surface.   i know i should use  **BRepLProp_SurfaceTool**, but i don't know how to master it!

it's my code as follwed. but it's a failure
```
def recognize_clicked(shp, *kwargs):     #
    """ This is the function called every time
    a face is clicked in the 3d view
    """
    for shape in shp: # select specific face 
        face1 = topods_Face(shape)
        surface = BRepAdaptor_Surface(face1)  #change topods_face type into brepadaptor_surface type
        Umin, Umax, Vmin, Vmax = breptools_UVBounds(face1)# obtain uv bound
        a,b,c=BRepLProp_SurfaceTool.Value(surface,0.2,0.3)
        print(a,b,c)
```

using this , i can obtain umax,umin,vmax,vmin
but **can't obtain  a,b,c(the information of point)**. maybe i don't use **BRepLProp_SurfaceTool** correctly

can i anyone help me?

**Comment by tpaviot** [comment]
can you please provide a full running example so that it can easily be tested/fixed
