### ISSUE TITLE
Can't import AIS_Manipulator from OCC.Core.AIS

### ISSUE THREAD

**Issue by HuaJianDeng** [tpaviot/pythonocc-core#596]
Dear Sir,

       I am new to pythonocc. When I recently working on my project, I realized it impossible to import AIS_Manipulator from OCC.Core.AIS. And I found that there is no ''AIS_Manipulator'' class in the file of AIS.py.  Am I doing anything wrong?  
       It will be very kind of you if you could offer me some suggestions.

**Comment by tpaviot** [comment]
AIS_Manipulator is available in OpenCascade 7.x whereas pythonocc wraps 6.9.

**Comment by HuaJianDeng** [comment]
@tpaviot Thank you ! Is there any update for pythonocc that including AIS_Manipulator ?
