### ISSUE TITLE
Transform a TopoDS_Edge

### ISSUE THREAD

**Issue by ViktorLajos** [tpaviot/pythonocc-core#60]
Hello!
I didn't find any forum where I can take my questions, so I write here.
I would like to rotate a TopoDS_Edge or Wire object, now I'm using BRepBuilderAPI_Transform for this, but it returns a Shape. If I ask the ShapeType of this object it says thats an Edge (6), but when I put this in the BRepBuilderAPI_MakeWire method, it fails. I hope you can help me, how to make this simple think.

**Comment by Jaredmmx** [comment]
I'm a very new user both to Python and PythonOCC but.. I need Utils module.. How can I make it available if it's not bundled with PythonOCC anymore?

Instructions about how to install https://github.com/tpaviot/pythonocc-utils would be very much appretiated. Can you help me? please?

**Comment by tophercf** [comment]
Try this on the command line:
 
git clone https://github.com/tpaviot/pythonocc-utils.git
cd pythonocc-utils
python setup.py install

It should be now be installed on your computer. Try using the python runtime: 
import OCCUtils
