### ISSUE TITLE
ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /usr/local/anaconda/bin/../lib/libTKernel.so.11)

### ISSUE THREAD

**Issue by shifujain** [tpaviot/pythonocc-core#601]
facing this error while running "python run_tests.py"

**Comment by tpaviot** [comment]
Did you ever used something named google before posting an issue ? Just try once, you'll get amazed, it's quite new I spell it g.o.o.g.l.e.

https://stackoverflow.com/questions/19471683/lib-libc-so-6-version-glibc-2-17-not-found

**Comment by shifujain** [comment]
Thanks
