### ISSUE TITLE
TypeError: in method 'Handle_Geom_Curve_DownCast', argument 1 of type 'Handle_Standard_Transient const &'

### ISSUE THREAD

**Issue by zhaowei699** [tpaviot/pythonocc-core#603]
` edgesExpr=TopExp_Explorer(shape,TopAbs_EDGE)
` 
 ` while edgesExpr.More():
` 
 ` `  ` ` print("next edge")
` 
 ` ` ` ` edge=topods.Edge(edgesExpr.Current())
` 
 ` `  ` `hs=BRep_Tool_Curve(edge)
 `
  ` `  ` `edgeHandle=Handle_Geom_Curve.DownCast(hs).GetObject()
`
  ` `  ` `print(edgeHandle.Location().X())
` 
 ` `  ` `edgesExpr.Next() `
**I try to get some curves' coordinate range, but I can't get geometry handle of curve by above script. see the following paragraph for the error information. Please kindly tell me how to do it, thanks a lot.
next edge**
Traceback (most recent call last):
  File "C:\ICCoverageTool_Qt5\ICCoverageTool.py", line 127, in toolbarButtonPressed
    self.calculateRange(shape)
  File "C:\ICCoverageTool_Qt5\ICCoverageTool.py", line 147, in calculateRange
    edgeHandle=Handle_Geom_Curve.DownCast(edge).GetObject()
TypeError: in method 'Handle_Geom_Curve_DownCast', argument 1 of type 'Handle_Standard_Transient const &'

**Comment by tpaviot** [comment]
Please provide a complete example.
