### ISSUE TITLE
CTRL-RMB dragging crashes qtDisplay

### ISSUE THREAD

**Issue by HenryFBP** [tpaviot/pythonocc-core#607]
Windows 7, using this conda install:

`conda install -c conda-forge -c tpaviot -c dlr-sc -c pythonocc -c oce -c ifcopenshell "pythonocc-core>=0.18.2" ifcopenshell automat==0.6.0 numpy`

Stack trace:
```Traceback (most recent call last):
  File "P:\lib\Anaconda3\lib\site-packages\OCC\Display\qtDisplay.py", line 292, in mouseMoveEvent
    self._display.DynamicZoom(abs(self.dragStartPos.x()),
TypeError: 'int' object is not callable
```

GIF available here: https://gyazo.com/72941b5cb025112c40cd1afca04987d8

**Comment by tpaviot** [comment]
Fixed in current master.
