### ISSUE TITLE
Reference to oce 0.17.2 in CMakeList.txt tag 0.18.1

### ISSUE THREAD

**Issue by NicolasFieldwire** [tpaviot/pythonocc-core#609]
Hello,

Thanks for all the nice work in this library.
I am investigating some segfault i got in a local docker environment, and i found this in CMakeLists.txt with tag 0.18.1.

set(CMAKE_SWIG_FLAGS ${CMAKE_SWIG_FLAGS} -DOCC_VERSION_HEX=0x060901) # oce0.17.2

I think the reference to 0.17.2 is is incorrect, am i right ?

Cheers

**Comment by tpaviot** [comment]
Right, it's oce 0.18.x, build upon occt6.9.1 (in hexa 0x060901). Fixed by commit 02e69a94255d184bf171488d965b1ccff39f8793

FYI a working Dockerfile for pythonocc is available at https://github.com/tpaviot/pythonocc-binderhub
