### ISSUE TITLE
PyPI package points to wrong url

### ISSUE THREAD

**Issue by Eothred** [tpaviot/pythonocc-core#61]
Sorry, this is probably not the place to post this report, but I could not figure out where to do it.

I noticed that there is a package "pythonOCC" on pypi which points to source code on Google. I suppose this is from some time ago when you perhaps used google to host your code instead of github. May I request that you either update the package or remove it from pypi? It is a bit confusing to find it with "pip search", but then not being able to install it.

**Comment by CromeX2020** [comment]
Trying to get this into a portable package, specifically WinPy. Can't get this to install

C:\WinPython-32bit-2.7.9.1\python-2.7.9>pip install pythonocc-core
Downloading/unpacking pythonocc-core
  Could not find any downloads that satisfy the requirement pythonocc-core
Cleaning up...
No distributions at all found for pythonocc-core
Storing debug log for failure in C:\WinPython-32bit-2.7.9.1\settings\pip\pip.log

**Comment by stuaxo** [comment]
I get the same error on Ubuntu 64 bit, with python 2.7.9

**Comment by fragmuffin** [comment]
Still getting the same error on Ubuntu 16.04

    $ sudo -H pip -vvv install pythonocc-core
    ...
      Analyzing links from page https://pypi.python.org/simple/pythonocc-core/
      Could not find a version that satisfies the requirement pythonocc-core (from versions: )
    ...

analysing the link...

    $ curl https://pypi.python.org/simple/pythonocc-core/
    <!DOCTYPE html><html><head><title>Links for pythonocc-core</title></head><body><h1>Links for pythonocc-core</h1></body></html>

yep, no useful information there... surely there's a fix, this post is years old... anyone?

**Comment by fragmuffin** [comment]
The answer is simple; support for `pip` seems to have been pulled (although, I don't know why).
The [official site](http://www.pythonocc.org/download/) recommends using `conda`.

**Comment by tpaviot** [comment]
Hi,

pip was never officially supported.

Prefer using conda

Thomas


2017-04-14 13:48 GMT+02:00 Peter Boin <notifications@github.com>:

**Comment by tpaviot** [comment]
@jf--- can you please remove the pip entry for pythonocc-core
