### ISSUE TITLE
Confused about v0.18.2

### ISSUE THREAD

**Issue by mantielero** [tpaviot/pythonocc-core#620]
I am a bit confused about v0.18.2. 

[pythonocc-demos](https://github.com/tpaviot/pythonocc-demos) page states:
* pythonocc-0.18.2 or later

But I don't find a [tagged version](https://github.com/tpaviot/pythonocc-core/tags) nor a [release](https://github.com/tpaviot/pythonocc-core/releases).

On the other hand it seems that there are [conda packages](https://anaconda.org/tpaviot/pythonocc-core) with v.0.18.2.

Could it be tagged?

**Comment by tpaviot** [comment]
For the latest pythonocc-core 0.18.1, pythonocc examples are bundled in the source code package or available as a separate archive at https://github.com/tpaviot/pythonocc-demos/releases/tag/untagged-f0a6c428382c46097ad9

There's not pythonocc-0.18.2 release yet.
