### ISSUE TITLE
BRepExtrema_ShapeProximity unusable?

### ISSUE THREAD

**Issue by tverho** [tpaviot/pythonocc-core#628]
I'm trying to use `BRepExtrema_ShapeProximity` for quick intersection detection. I can run it, but the only way to get output are the functions `OverlapSubShapes1()` and `OverlapSubShapes2()`. Their return type is `BRepExtrema_MapOfIntegerPackedMapOfInteger`, which doesn't seem to have a proper wrapper. I cannot access any of its methods, even to see if it's empty or not.

`BRepExtrema_SelfIntersections` has a similar problem.

**Comment by tpaviot** [comment]
can u please upload a ready-to-test sample code

**Comment by tverho** [comment]
Sure, here you go:

```
from OCC.gp import gp_Pnt
from OCC.BRepPrimAPI import BRepPrimAPI_MakeBox
from OCC.BRepMesh import BRepMesh_IncrementalMesh
from OCC.BRepExtrema import BRepExtrema_ShapeProximity
 

box1 = BRepPrimAPI_MakeBox(gp_Pnt(0, 0, 0), gp_Pnt(2, 2, 2)).Shape()
box2 = BRepPrimAPI_MakeBox(gp_Pnt(1, 1, 1), gp_Pnt(3, 3, 3)).Shape()

# Create meshes for the proximity algorithm
deflection = 1e-3
mesher1 = BRepMesh_IncrementalMesh(box1, deflection)
mesher2 = BRepMesh_IncrementalMesh(box2, deflection)
mesher1.Perform()
mesher2.Perform()

tolerance = 0.1
isect_test = BRepExtrema_ShapeProximity(box1, box2, tolerance)
isect_test.Perform()

overlaps = isect_test.OverlapSubShapes1()

# overlaps doesn't have any methods like Size()
print(dir(overlaps))
```

**Comment by tpaviot** [comment]
Confirmed.

**Comment by tpaviot** [comment]
Same in latest 7.4.0beta2 release

**Comment by tpaviot** [comment]
This works in 7.4.0beta2, but the ```NCollection_StlIterator``` class is not wrapped, and it's not possible to access faces that overlaps. See related issue #743

**Comment by tpaviot** [comment]
Commit 4ae36a6aaf53c4f7af749b796ceca56466c2d727 fixes this issue.

I added an example core_geometry_overlap at https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_geometry_overlap.py (in red, faces that overlap, usefull to look for clashes)

![core_goemetry_overlap](https://user-images.githubusercontent.com/660130/71730117-a8ebd080-2e41-11ea-84a2-04550b9ba983.png)

**Comment by tverho** [comment]
I can't test it because the latest master requires cmake 3.12 and my distro (Ubuntu 18.04 LTS) only has 3.10. However, I guess I don't need to test it to conclude that the bug is fixed and the issue can be closed. Nice work!
