### ISSUE TITLE
Installation on windows with conda

### ISSUE THREAD

**Issue by gregorito** [tpaviot/pythonocc-core#644]
Hello, 
I have tried to install on a windows 10 machine with the following:
 conda install -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core==0.18.1
I can import OCC without trouble, the examples are "running" if i change OCC.Core to OCC.
The issue I am having is that nothing is being displayed, no windows appearing nothing.
Any ideas ?
Greg

**Comment by Vishnu-C** [comment]
Check if this helps

https://github.com/tpaviot/pythonocc-core/issues/551#issuecomment-414378610

**Comment by gregorito** [comment]
Solved with a fresh install of anaconda, from what i've seen the problem was my install of pyqt with a conflict on QOpenGL... 
Thanks
