### ISSUE TITLE
Typo in wxDisplay PythonOCC 0.18.2

### ISSUE THREAD

**Issue by Durksz** [tpaviot/pythonocc-core#646]
When initializing the wxViewer3d in PythonOCC 0.18.2 it throws an error "'Viewer3d' object has no attribute 'display_trihedron' "

The OCCviewer.py does not have a function with the name "display_triedron" 

If I change the name in wxDisplay.py from 'display_trihedron' to 'display_triedron' it works again (in code line 145).

**Comment by tpaviot** [comment]
Fixed by commit 6d2710d67fdb95fe6effaff5e15dc11d503f20c0
