### ISSUE TITLE
no real coordinate model is displayed in x3dom

### ISSUE THREAD

**Issue by liuxin2322** [tpaviot/pythonocc-core#647]
when i import my model into brower, no real coordinate model is displayed just like Fig2.
how can i process the issue?
***real coordinate model mean like this(Fig1)**** 
![特殊t](https://user-images.githubusercontent.com/42459125/54535671-fc338600-49c9-11e9-92e7-29fbd8905da0.jpg)
Fig.1 real coordinate model
![githun](https://user-images.githubusercontent.com/42459125/54535526-a9f26500-49c9-11e9-823e-892a2622206b.jpg)
 Fig.2 display panel without real coordinate model

**Comment by tpaviot** [comment]
Fixed by commit 1e313185d882576afb4cfc603cbdb615940a8a89

![x3dom_axes_plane](https://user-images.githubusercontent.com/660130/56484366-85f5d800-64cf-11e9-8b47-3c9361b8fe68.png)
