### ISSUE TITLE
OCC.BRepClass.BRepClass_FaceClassifier does not get wrapped 

### ISSUE THREAD

**Issue by sdh4** [tpaviot/pythonocc-core#650]
The 3D face classifier OCC.BRepClass.BRepClass_FaceClassifier is not currently wrapped by the bindings. Its superclass OCC.BRepClass.BRepClass_FClassifier that does parametric point classification does get wrapped by the bindings.

**Comment by tpaviot** [comment]
Confirmed.

Fixed by commit 3a77a98d

**Comment by lambrtz** [comment]
Hello, sorry for necro-ing an old post, but I cannot seem to find BRepClass_FaceClassifier in miniconda, channel conda-forge. Am I missing something?

**Comment by lambrtz** [comment]
I just noticed that BRepClass_FaceClassifier disappears again after this commit: ce671d360676aa3750c856c4d8252383bc897528 
Is it possible that it is re-introduced to pythonocc?

**Comment by tpaviot** [comment]
done, see commit 902279387bc58152d4c6f8b46ee271f1efb46098
