### ISSUE TITLE
 the "read_step_file_with_name_and_colors" have some problem,it cannot read the name of shapes from my STEP

### ISSUE THREAD

**Issue by w-z-l** [tpaviot/pythonocc-core#673]
def _get_label_name(lab):
        entry = TCollection_AsciiString()
        TDF_Tool.Entry(lab, entry)
        n = TDataStd_Name()
        lab.FindAttribute(TDataStd_Name_GetID(), n)
        if n is not None:
            return n.Get().PrintToString()
        return "No Name"

**Comment by tpaviot** [comment]
issue related to #713
