### ISSUE TITLE
Gear Meshing

### ISSUE THREAD

**Issue by efirvida** [tpaviot/pythonocc-core#687]
Hello everyone:
Maybe this is not the right place to ask, for hints but is the place that I know ;)
I need to create an FEA model of spur-gears, let's say that I know how to model the gears, improving my project: https://github.com/efirvida/python-gearbox . then I want to mesh the gears like this pictures;

![image](https://user-images.githubusercontent.com/4184620/66955480-6aa7f780-f030-11e9-8f4c-f323f0ecfa9b.png)

![image](https://user-images.githubusercontent.com/4184620/66955539-8e6b3d80-f030-11e9-80b5-b94f956be44b.png)

I know how to do all the cad procedures... but I don´t know If I can use PythonOCC to mesh the geometry as I want.

Thanks in advance

**Comment by rainman110** [comment]
You probably should have a look at GMSH: http://gmsh.info/

It also supports geometries from OpenCASCADE.

**Comment by tpaviot** [comment]
@efirvida Have a look at the ipython notebook about how to use both pythonocc and gmsh 
https://github.com/tpaviot/pythonocc-demos/blob/master/jupyter_notebooks/occ_triangle_mesh_gmsh.ipynb

Try online at
https://mybinder.org/v2/gh/tpaviot/pythonocc-binderhub/master and run jupyter_notebooks/occ_triangle_mesh_gmsh.ipynb
