### ISSUE TITLE
cmake C compiler check

### ISSUE THREAD

**Issue by JanssensNick** [tpaviot/pythonocc-core#696]
I run 
_cmake .._
in the cmake-build directory, I get the error that my C compiler doesn't work (The C-compiler is not able to compile a simple test program). However, I wrote a simple test program myself and compiled it with the specified C compiler, and it works.
Any thoughts?
Note: if I overrule the test manually, the final make install command does not install anything, so simply overruling the test is not an option.
Note: my OS is Windows 10

**Comment by rainman110** [comment]
This is not a pythonocc issue, but general to cmake. CMake performs some checks, whether to compile successfully files.

I often had this, when using the msvc build tools without windows sdk. Please file this issue at the cmake bug tracker.
