### ISSUE TITLE
Tesselator

### ISSUE THREAD

**Issue by looooo** [tpaviot/pythonocc-core#7]
from OCC.Visualization import Tesselator
from OCC.BRepPrimAPI import BRepPrimAPI_MakeBox
shape = BRepPrimAPI_MakeBox(1,1,1).Shape()
tes = Tesselator(shape)
tes.VerticesList()

returns :"Swig Object of type 'float *' at 0x2613ae0"

is there a way to get these values in python?

**Comment by jf---** [comment]
@tpaviot , can we close this in regard to the recent contrib in the Tesselator class?

**Comment by tpaviot** [comment]
Yes issue can be closed

**Comment by jf---** [comment]
@tpaviot , I would have, but do not have the rights to do so...

**Comment by tpaviot** [comment]
Fixed by PR #165
