### ISSUE TITLE
Demos: Replace Prs3d_Presentation with Graphic3d_Structure

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-core#701]
Required by demo core_topology_glue

**Comment by tpaviot** [comment]
@rainman110 Prs3d_Presentation is deprecated in occt740. You just have to replace it with ```Graphic3d_Structure```

**Comment by rainman110** [comment]
Thanks for the info! I think I already did this somewhere, but I  forgot about it :D

**Comment by rainman110** [comment]
It's part of "test against all demos". I am working to get all demos running. This is already fixed, but not commited yet
