### ISSUE TITLE
Running core_mesh_surfatic.py Under Windows

### ISSUE THREAD

**Issue by ManyAngledOne** [tpaviot/pythonocc-core#705]
Hi,

I've been trying to use Conda to get a python 3.x win64 build of pythonocc which can run this demo file:
https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_mesh_surfacic.py

I've managed to install versions 0.18.2, 0.18.1, 0.17.3 from various channels on conda cloud: https://anaconda.org/search?q=platform%3Awin-64+pythonocc

But none of them can run this file out of the box.

0.18.2 cannot find OCC.Core.SMESH, presumably because all the 0.18.2 binaries were built without SMESH support

0.18.1 and 0.17.3 can't find OCC.Core and when I modify the example by replacing "OCC.Core." with "OCC." to get around the refactoring, then it cannot find a module called '_MeshVS'

I can run this file (without the display stuff) in a google colab notebook (ubuntu) just fine using the build of 0.18.2 in tpaviot's channel.

Is there somewhere I can get a binary release of pythonocc which can run this file under windows?

Thanks.

**Comment by tpaviot** [comment]
The core_mesh_surfacic example is depreacted, SMESH support was dropped in the latest release.
