### ISSUE TITLE
Fix unittests for OCCT 7.4.0

### ISSUE THREAD

**Issue by rainman110** [tpaviot/pythonocc-core#712]
There is only one issue left:
 - Wrong edge counting in TopologyExplorer class

Is this really a bug of pythonocc?

**Comment by tpaviot** [comment]
No I'm not sure. The TopologyExplorer class seems to work as expected, since it is widely used in the examples. So I think this test should simply be removed (actually commented out, let's keep some kind of memory related to this story)
