### ISSUE TITLE
bug:step part name return blank

### ISSUE THREAD

**Issue by liuxin2322** [tpaviot/pythonocc-core#713]
version:pythonocc740beta  os:linux 64 
source code:
```python
from OCC.Display.SimpleGui import init_display
from OCC.Extend.DataExchange import read_step_file_with_names_colors
display, start_display, add_menu, add_function_to_menu = init_display()
shapes_labels_colors=read_step_file_with_names_colors('UiRS.1 - Robot Arm 3DOF.STEP')




for shpt_lbl_color in shapes_labels_colors:
    label, c = shapes_labels_colors[shpt_lbl_color]

    display.DisplayShape(shpt_lbl_color,color=c)
start_display()
```
console log :

```Name : 
Name : 
    shape color Name & RGB:  class<'Quantity_Color'> 307 0.7921568751335144 0.8196078538894653 0.9333333373069763
....
```

it seems part name return nothing or blank
test model:

`'UiRS.1 - Robot Arm 3DOF.STEP'`
[testStep.zip](https://github.com/tpaviot/pythonocc-core/files/3869053/testStep.zip)

hope  to solve this bug :)

**Comment by tpaviot** [comment]
Honestly, I don't kow. I spent *dozains of hours*, during last summer, trying to figure out what's going on with CAF/XDE/TDF_Labels and so on, it's a pure mystery. I don't undesrtand how that work, definitely, and I'm afraid I can't help

**Comment by liuxin2322** [comment]
@tpaviot :sob:   I want to help，but it's a huge project（maybe from begin to learn wrapper cpp）

**Comment by tpaviot** [comment]
I tested with the STEP file provided, here is what I get.

![capt](https://user-images.githubusercontent.com/660130/70804631-41e57980-1db7-11ea-82e9-499f3f7ce4ec.png)

Is it he expected colors ?

**Comment by liuxin2322** [comment]
> I tested with the STEP file provided, here is what I get.
> 
> ![capt](https://user-images.githubusercontent.com/660130/70804631-41e57980-1db7-11ea-82e9-499f3f7ce4ec.png)
> 
> Is it he expected colors ?

It's weird .     using other web view  application, i get following pic:
![QQ截图20191213220649](https://user-images.githubusercontent.com/42459125/70806102-8a238c80-1df5-11ea-8ce8-66c60d848574.png)

**Comment by tpaviot** [comment]
The lightning in simple display may affect shape rendering, I'll check with the x3d exporter

**Comment by tpaviot** [comment]
Here is the result in a Chrome window

![capt](https://user-images.githubusercontent.com/660130/70809237-a6a5d180-1dc1-11ea-8c13-3e5b2e31279d.png)

I'm not sure your renderer can be trusted more than mine. STEP and colors is a big deal. I used to work with a guy from NIST, he's working on a set of test files. Each software I tested (commercial Cat, SW, Autodesk inventor and free such as FreeCad), all of them render colors a different way.

**Comment by liuxin2322** [comment]
@tpaviot you're right. different render display different，the returned data of color is mostly accurate because of x3d result.      but I have to say, qtdisplay may  have some implicit bugs

**Comment by tpaviot** [comment]
Fixed.

**Comment by liuxin2322** [comment]
@tpaviot :+1:
