### ISSUE TITLE
ImportError: cannot import name 'Handle_Geom2d_BSplineCurve'

### ISSUE THREAD

**Issue by hussainkadori** [tpaviot/pythonocc-core#721]
Hi,
Where Can I find the Handle_Geom2d_BSplineCurve in the new version?

**Comment by tpaviot** [comment]
You don't need handles anymore, just use the Geom2d_BSplineCurve object.

See for instance how the classic bottle example was ported https://github.com/tpaviot/pythonocc-demos/commit/e59acdce5720d84ce76134789b48c268e36446d6#diff-68b70730ce65eb74e098809766ab3d0d

You can also have a look at #720

**Comment by hussainkadori** [comment]
Thanks. 
Solved 👍
