### ISSUE TITLE
pythonocc version 7.4.0-beta2 TCollection_AsciiString fails

### ISSUE THREAD

**Issue by Brently-Mills** [tpaviot/pythonocc-core#734]
Hello,
 Using Anaconda 5.2.0 on Windows 10 with Pythonocc 7.4.0-beta 2

When calling TCollection_AsciiString the following error is returned

Unable to get repr for <class 'OCC.Core.TCollection.TCollection_AsciiString'>

This is in the OCC.Extend package for module DataExchange.py line 142.

Thank you!
Brent

**Comment by tpaviot** [comment]
Right, there's an issue with __repr__ method for this class, fix is on the way
