### ISSUE TITLE
Intersect point cloud model with ifc/step model

### ISSUE THREAD

**Issue by Selo251** [tpaviot/pythonocc-core#736]
Hi all,
For my research project, I want to intersect a point cloud model with ifc model. To do this, I want to make small cubes of each point of the point cloud data and intersect this with the surface of the ifc/step model. Hereby, I see that core_display_point_cloud.py and core_geometry_point_from_intersection.py comes handy to use as a base construction. As I am not a programmer, I want to know how it is possible to:
- Make cubes of each points of the .pcd file
- Intersect this to the plane
- Calculate how many points are intersected

**Comment by tpaviot** [comment]
Yes it is, however occt  data structure relies on a brep representation, not voxels. I think vtk is more suitable for your problem.
