### ISSUE TITLE
Error in importing module with 7.4.0beta2

### ISSUE THREAD

**Issue by zjiang0529** [tpaviot/pythonocc-core#737]
Hello, 

Recently, I have built the source code of the new version pythonocc-core 7.4.0beta2. 
Before I have been using the pythonocc-core-0.18.1 version. 
And I notice that I can no longer call the module by using "OCC.BRep" for example, 
I should call modules by using "OCC.Core.BRep". This is not really an issue, however I 
got the following error when I import OCC.Core.BRep : No module named '_BRep'

Could you help me to fix this issue ? Thanks a lot. 

Zhifan Jiang

**Comment by tpaviot** [comment]
What's your OS ? Did you also compiled opencascade by your own ? Can you please insert the full log ?

**Comment by zjiang0529** [comment]
Thank you for your reply. I work on Ubuntu 18.04 LTS, with Python 3.7 and Conda environment. 
Yes, I also compiled opencascade-7.4.0 and I defined correctly the built occt-install directory in cmake 
when I was building pythonocc-core. What kind of log should I insert ?

**Comment by zjiang0529** [comment]
I am wondering maybe it's a problem of libTKernel, I did not notice that before. 
![Screenshot from 2019-12-20 15-07-33](https://user-images.githubusercontent.com/24623660/71260319-e4af7200-233a-11ea-920b-12f04b40c1a3.png)
![Screenshot from 2019-12-20 15-08-46](https://user-images.githubusercontent.com/24623660/71260320-e4af7200-233a-11ea-9eee-e97e0b2fda5e.png)

**Comment by tpaviot** [comment]
1. Be sure you add occt lib directory to the $PATH environment variable ;

2. Be sure the occt libraries in your $PATH are 7.4.0 (if ever you work with concurrent versions of occt, that might cause such issues)

**Comment by tpaviot** [comment]
for instance, in my ```.bashrc```, I have inserted the following line
```
export LD_LIBRARY_PATH=/opt/build/occt740/lib:$LD_LIBRARY_PATH
```

**Comment by zjiang0529** [comment]
Thanks a lot! I think that's why it could not find the lib files found in occt lib directory. 
I have added the occt lib directory in $PATH variable and the issue has been fixed. 
I have just one more question : instead of calling OCC.BRep, all the modules are packed in OCC.Core. Is this a new feature and a choice by your part for this new version ?

**Comment by tpaviot** [comment]
It's a change in the package structure. You have to move all your ```import OCC.xxx``` to ```import OCC.Core.xxx```
