### ISSUE TITLE
Option for rendering edges in JupyterRenderer as continuous in addition to dashed

### ISSUE THREAD

**Issue by Krande** [tpaviot/pythonocc-core#751]
Hello,

I came across some issues using the JupyterRenderer to render a simple wire (comprised of 2 edges) using the following code (and pythnocc 7.4.0RC1)

```
from OCC.Core.gp import gp_Pnt
from OCC.Extend.ShapeFactory import make_wire
from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeEdge

h = 0.18
wbtn = 0.033
p1 = (0, 0, 1)
p2 = (0, -h, 1)
p3 = (wbtn, -h, 1)


e1 = BRepBuilderAPI_MakeEdge(gp_Pnt(*p1), gp_Pnt(*p2)).Edge()
e2 = BRepBuilderAPI_MakeEdge(gp_Pnt(*p2), gp_Pnt(*p3)).Edge()

mywire = make_wire([e1, e2])

# Visualize using SimpleGui
from OCC.Display.SimpleGui import init_display
display, start_display, add_menu, add_function_to_menu = init_display()
display.EraseAll()
display.DisplayShape(mywire)
display.FitAll()
start_display()

# Visualize using JupyterRenderer
my_renderer = JupyterRenderer(size=(800, 600))
my_renderer.DisplayShape(mywire, update=False, render_edges=False)
my_renderer.Display()
```

This is visualized just fine using the SimpleGui in the code above

![image](https://user-images.githubusercontent.com/9642232/71782647-e33da500-2fdc-11ea-94f5-4271c2bea8a5.png)

However the JupyterRenderer resulted displaying only one of the edges as shown below:

![image](https://user-images.githubusercontent.com/9642232/71782694-56dfb200-2fdd-11ea-99a3-350959f77374.png)

Now the problem (as far as I can tell) is the dash-spacing in the default dashed line geometry in the JupyterRenderer. By editing the above example using larger numbers (as shown below) I am able to display both edges.

```
from OCC.Core.gp import gp_Pnt
from OCC.Extend.ShapeFactory import make_wire
from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeEdge

h = 100
wbtn = 10
p1 = (0, 0, 1)
p2 = (0, -h, 1)
p3 = (wbtn, -h, 1)


e1 = BRepBuilderAPI_MakeEdge(gp_Pnt(*p1), gp_Pnt(*p2)).Edge()
e2 = BRepBuilderAPI_MakeEdge(gp_Pnt(*p2), gp_Pnt(*p3)).Edge()

mywire = make_wire([e1, e2])
```

![image](https://user-images.githubusercontent.com/9642232/71782738-c2c21a80-2fdd-11ea-9fff-10bf6bd3bf7e.png)

I have tried debugging in order to figure out where the dashed line geometry is being set, however I have yet to find exactly where the dashed line geometry is applied. It may be a long shot but, could it somehow be related to the Tessalator defined here?

https://github.com/tpaviot/pythonocc-core/blob/076b22229c73905503c28c46c125e7fe35cc715e/src/Display/WebGl/jupyter_renderer.py#L539-L543

To circumvent this, would it be possible to add an option to set a continuous line geometry representation as an alternative to the default dashed line geometry?

Best Regards
Kristoffer

**Comment by tpaviot** [comment]
I can't reproduce the issue : in the second case, I dont' see anything, no dashed line.

Edge display style depends on the "Material" affected to the shape. It's basically a ```LineBasicMaterial``` and I don't see any dash option. It's defined at the python level, in the jupyter_renderer

**Comment by Krande** [comment]
Ah okay, 

that could be my bad. For the figure I moved the geometry a bit on the z-axis in order for the dashed line not to be covered by the primary axis 

```
from OCC.Core.gp import gp_Pnt
from OCC.Extend.ShapeFactory import make_wire
from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeEdge
from OCC.Display.WebGl.jupyter_renderer import JupyterRenderer

h = 100
wbtn = 10
p1 = (0, 0, 1)
p2 = (0, -h, 1)
p3 = (wbtn, -h, 1)


e1 = BRepBuilderAPI_MakeEdge(gp_Pnt(*p1), gp_Pnt(*p2)).Edge()
e2 = BRepBuilderAPI_MakeEdge(gp_Pnt(*p2), gp_Pnt(*p3)).Edge()

mywire = make_wire([e1, e2])

my_renderer = JupyterRenderer(size=(800, 600))
my_renderer.DisplayShape(mywire, update=False, render_edges=False)
my_renderer.Display()
```

![image](https://user-images.githubusercontent.com/9642232/71783425-d9b93a80-2fe6-11ea-9432-84989024c31a.png)

Are you still not seeing the dashed line?

**Comment by rainman110** [comment]
@tpaviot i also have the dashed line issues for curves only. 

The reason is the wrong opengl enum used for line renderings. The fix is a one liner!

**Comment by tpaviot** [comment]
@rainman110 Where is this enum defined or used ?

**Comment by tpaviot** [comment]
I confirm that curves (only, not shape edges) are rendered using a dashed line.

**Comment by tpaviot** [comment]
I think it comes from the line

https://github.com/tpaviot/pythonocc-core/blob/master/src/Display/WebGl/jupyter_renderer.py#L522

It's currently
```
edge_material = LineBasicMaterial(color=color, linewidth=2, fog=True)
```
it should be
```
edge_material = LineBasicMaterial(color=color, linewidth=1)
```

I can't run a test today, can you @Krande try to manually modify your jupyter_renderer.py and check the result ?

**Comment by Krande** [comment]
Unfortunately from what I can tell removing "fog=True" did not change the line representation.

The altered code
```
print('fog is not included')
edge_material = LineBasicMaterial(color=color, linewidth=1)
edge_lines = LineSegments(geometry=edge_geometry, material=edge_material)
```
resulted in
![image](https://user-images.githubusercontent.com/9642232/71814690-7fb78400-307d-11ea-9ef5-85f0d4d7eeb7.png)

I will continue debugging the python part of the code to see if I can track down the source of the dashed lines.

**Comment by rainman110** [comment]
@tpaviot LineSegments must be replaced by Line.

Then, you should not have any dashed lines anymore.

**Comment by Krande** [comment]
That worked like a charm!

```
print('Line replacing LineSegment')
edge_material = LineBasicMaterial(color=color, linewidth=1)
edge_lines = Line(geometry=edge_geometry, material=edge_material)
```

resulted in the expected shape

![image](https://user-images.githubusercontent.com/9642232/71831241-c373b300-30a8-11ea-86f4-f701bf5ad703.png)

For my part, feel free to close this issue!

Best regards
Kristoffer

**Comment by rainman110** [comment]
@Krande feel free to contribute a pull request to fix this problem ;-)

**Comment by Krande** [comment]
Sure, I'll give it a shot!

**Comment by tpaviot** [comment]
```LineSegments2``` also works. I dont' know which one is better between ```Line``` and ```LineSegments2```. I'll push a fix tomorrow. I also other change to upload.

@rainman110 If you have comments/requests related to the jupyter, it's a good time I will work on that topic this week, it's been a while I didn't work on this part of the project.

**Comment by rainman110** [comment]
Line is definitely the right choice. See the three.js documentation https://threejs.org/docs/#api/en/objects/Line

**Comment by rainman110** [comment]
> If you have comments/requests related to the jupyter renderer, it's a good time, I will work on that topic this week, it's been a while I didn't work on this part of the project.

It's been a while, since I modified the jupyter renderer for us to work better. This is what I changed:
 - Added function to remove shapes.
 - I think I also changed a bit the "fit objects to view" functionality.

I am right now on a conference and can not really work on anything, therefore I can give you only tiny information right now.

**Comment by tpaviot** [comment]
@rainman110 Is this code publicly available somewhere ?
