### ISSUE TITLE
TypeError: argument 1 has unexpected type 'NoneType' Inbox 	x

### ISSUE THREAD

**Issue by phangelder** [tpaviot/pythonocc-core#763]
Hope you can advise how to solve the following error

  File "K:/Python Collections/Test/myOcc/main.py", line 58, in __init__
    self.displaySphereAct.triggered.connect(self.sphere(display))
TypeError: argument 1 has unexpected type 'NoneType'

[test.zip](https://github.com/tpaviot/pythonocc-core/files/4086818/test.zip)

**Comment by bricway** [comment]
Regarding the `import`:
load_backend(..) has to imported before importing `qtViewer3d`. This is missing in your example. Therefore example cannot work.

Regarding Qt-Stuff and Python in General:
You just define totally wrong the lambda-function. With

`self.displaySphereAct.triggered.connect(lambda: self.sphere(display.DisplayShape))` 

it simply works.

As your question/problem is very basic/simple you should rearly start to learn first Python, then Qt and after you can start with pythonocc. These kind of questions are better to be placed on  [stackoverview](https://stackoverflow.com/search?q=pyqt).
