### ISSUE TITLE
incorrectly imported step files

### ISSUE THREAD

**Issue by michele-arrival** [tpaviot/pythonocc-core#775]
Hi, 

There seems to be a discrepancy when loading some step files, in that not all shapes are fetched by the function `read_step_file` (in fact only the first one is), where instead `read_step_file_with_names_colors` loads all shapes correctly.

The file that reproduces the error can be obtained from this dataset: https://deep-geometry.github.io/abc-dataset/
Any of the step files in the dataset triggers the issue, however to cut it short one can simply download the ste file in the front page: https://deep-geometry.github.io/abc-dataset/data/00000050_80d90bfdd2e74e709956122a_step_000.step 

To reproduce one can run `core_load_step_ap203.py` from the demos repo with this file. The visualized part will be like this - both when doing `import_as_one_shape` and `import_as_multiple_shapes`
![image](https://user-images.githubusercontent.com/54891577/74427286-b3d94e00-4e4e-11ea-83af-ba080e157bc5.png)

whereas both samples `core_load_step_ap203_ocaf.py` and `core_load_step_with_colors.py` load the right number of shapes:
![image](https://user-images.githubusercontent.com/54891577/74427362-db301b00-4e4e-11ea-9334-f768348c2526.png)
![image](https://user-images.githubusercontent.com/54891577/74427370-e125fc00-4e4e-11ea-8249-bf392593185e.png)

cheers

**Comment by qunat** [comment]
som step file you want to load must be saved stp not step

**Comment by tpaviot** [comment]
Thanks for the report , investigating

**Comment by jf---** [comment]
> The file that reproduces the error can be obtained from this dataset: https://deep-geometry.github.io/abc-dataset/

@michele-arrival that is an **unbelievable** resource, *wow*! 
can we perhaps invite you to write a post on [pythonocc.org](http://www.pythonocc.org/) on how you are using this dataset and what the connection to `pythonocc` is? 
I'm incredibly curious ;)

**Comment by michele-arrival** [comment]
> > The file that reproduces the error can be obtained from this dataset: https://deep-geometry.github.io/abc-dataset/
> 
> @michele-arrival that is an **unbelievable** resource, _wow_!
> can we perhaps invite you to write a post on [pythonocc.org](http://www.pythonocc.org/) on how you are using this dataset and what the connection to `pythonocc` is?
> I'm incredibly curious ;)

Hi and thanks for the interest! 
I haven't entirely defined what the use of pythonocc will be for me. For the time being i was looking for a python module to render parametric models and pythonocc seemed to be a good choice for that. In the future I will possibly look at geometric - or even semantic - classification of the parts and identify what they are useful for. It's an ongoing project, but I'm happy to take you up on the offer in the future once I have a clearer picture. Thanks indeed for the proposal!

@tpaviot Thanks for the fix in the new release!
