### ISSUE TITLE
'AIS_Shape' object has no attribute 'GetObject'

### ISSUE THREAD

**Issue by Abhinav-Anil** [tpaviot/pythonocc-core#784]
Trying to rotate the step file at 90 degree, but getting the error
Below I paste code as well as error.Please assist.

from math import pi

from OCC.TopAbs import TopAbs_ON
from OCC.TopLoc import TopLoc_Location
from OCC.gp import gp_Ax1, gp_Pnt, gp_Dir, gp_Trsf
from OCC.AIS import AIS_Shape

from OCC.STEPControl import STEPControl_Reader
from OCC.Display.SimpleGui import init_display

path = "/home/abhinav/Downloads/OUTPUT OF ALU PART (extract.me)/OUTPUT OF ALU PART/ALU_PART.stp"
step_reader = STEPControl_Reader()
step_status = step_reader.ReadFile(path)
step_reader.TransferRoot()
step_shape = step_reader.Shape()

display, start_display, add_menu, add_function_to_menu = init_display()
display.SetSelectionMode(TopAbs_ON)
step_ais_shape_handle = display.DisplayShape(step_shape, update=True)
step_ais_shape = step_ais_shape_handle.GetObject()

def rotate(shp, *kwargs):
	print (shp) 
	print (kwargs) 
	if shp == []: return
	aiShape = AIS_Shape(shp[0]) # TopoDS_Shape -> AIS_Shape
	aiShape.AcceptShapeDecomposition = (lambda: True)
	aisHandle = aiShape.GetHandle() # AIS_Shape -> Handle

	point     = gp_Pnt(0., 0., 0.)
	direction = gp_Dir(0., 1., 0.)
	ax1 = gp_Ax1(point, direction)

	aisHandle = step_ais_shape_handle 

	transform = gp_Trsf()
	angle = 90.0
	n_rotations = 200
	for i in range(n_rotations):
		transform.SetRotation(ax1, angle)
		location = TopLoc_Location(transform)
		display.Context.SetLocation(aisHandle, location)
		display.Context.UpdateCurrentViewer()
		angle += 2*pi / n_rotations

display.register_select_callback(rotate)
start_display()

Traceback (most recent call last):
  File "/home/abhinav/Documents/cad/rotation.py", line 22, in <module>
    step_ais_shape = step_ais_shape_handle.GetObject()
AttributeError: 'AIS_Shape' object has no attribute 'GetObject'

**Comment by tpaviot** [comment]
```GetObject``` and ```GetHandle``` methods are deprecated in latest 7.4.0 release. Read the ```transparent_handles``` section at https://github.com/tpaviot/pythonocc-core/wiki/Porting-from-0.18.x-to-7.4.0
