### ISSUE TITLE
support pip install pythonocc-core

### ISSUE THREAD

**Issue by hxse** [tpaviot/pythonocc-core#796]
Why exclude via pip install, that is very strange.
Could you give me an explanation?

**Comment by tpaviot** [comment]
Where did you read the pip install is "excluded" ? It's not a choice or a decision we made. I'd be glad that you contribute an installation process using pip.

**Comment by adam-urbanczyk** [comment]
This project might be interesting for you @hxse https://github.com/regro/conda-press

BTW: I think pip is not really suited for a package with complex non-python dependencies.

**Comment by tpaviot** [comment]
@adam-urbanczyk thank you for the link, I'll test and report here the result
