### ISSUE TITLE
is GLTFexporter   available？？

### ISSUE THREAD

**Issue by liuxin2322** [tpaviot/pythonocc-core#808]
hope！

**Comment by tpaviot** [comment]
Currently, only a GLTF importer is available https://www.opencascade.com/doc/occt-7.4.0/refman/html/package_rwgltf.html, an exporter is being add upstream, see for instance http://git.dev.opencascade.org/gitweb/?p=occt.git;a=blob;f=src/RWGltf/RWGltf_CafWriter.cxx;h=80bd70547431159913ec0d2b5b9c3c1a7e98778c;hb=HEAD but it's not released yet

**Comment by tpaviot** [comment]
I think we have to wait for the next occt release

**Comment by seyfeb** [comment]
Has there been any progress on this since the issue was opened/closed?

**Comment by Sadiq-Naizam** [comment]
Any update on this? Is there a GLTF exporter yet?
