### ISSUE TITLE
Missing some Python OCC module .

### ISSUE THREAD

**Issue by dev1intellial** [tpaviot/pythonocc-core#81]
Downloaded pythonOCC-0.16.0-win32-py34.exe and installed. After installation found some module is missing (for example - OCC.STEPCAFControl, OCC.TDocStd). How to get this module?

Please help.

**Comment by tpaviot** [comment]
Please use the examples that come with the release. The examples from the master branch require pythonocc compiled from the master branch.

**Comment by dev1intellial** [comment]
How to compile pythonocc?
