### ISSUE TITLE
Display shape without wireframe

### ISSUE THREAD

**Issue by godjenka** [tpaviot/pythonocc-core#820]
This one must be easy to solve, but I don't seem to find the solution. I'd like to display a shape without wireframe. How can I do it?

**Comment by tpaviot** [comment]
By default, shapes in the SimpleGui are displayed in shaded mode, not wireframe except if you explicitly ask for.

**Comment by VictorLamoine** [comment]
I think he meant displaying the shape solid with no edges/wires displayed.

**Comment by tpaviot** [comment]
ah, ok, in this case, just add this line:

```python
display.default_drawer.SetFaceBoundaryDraw(True)
```

**Comment by tpaviot** [comment]
I confess this is not straightforward, I added an example at https://github.com/tpaviot/pythonocc-demos/commit/0a97f2d805adb48fde93a92291c21a02b1bb01b3

**Comment by tpaviot** [comment]
Please @godjenka close the issue if ever the provided solution fixes the issue

**Comment by godjenka** [comment]
Yes, this is what I meant, thanks!
