### ISSUE TITLE
can't import TPrsStd_AISViewer and TPrsStd_AISPresentation from TPrsStd library

### ISSUE THREAD

**Issue by Padavnav** [tpaviot/pythonocc-core#834]
Here is the piece of code which showing attribute error in accessing these functions

        aisview = TPrsStd.TPrsStd_AISViewer().New(self.doc.top_label,self.context)
        self._ais_pres = TPrsStd.TPrsStd_AISPresentation().Set(self.doc.top_label, XCAFPrs_Driver().GetID())

AttributeError: module 'OCC.Core.TPrsStd' has no attribute 'TPrsStd_AISViewer'

**Comment by tpaviot** [comment]
I confirm that this class is explicitly currently excluded from the wrapper. I have to check why (I don't remember)

**Comment by tpaviot** [comment]
Fixed by commit c3105e585d8ccc1ba20b4973aad61d0d949d1c45
