### ISSUE TITLE
Origin from step file

### ISSUE THREAD

**Issue by Abhinav-Anil** [tpaviot/pythonocc-core#839]
@tpaviot and @jf---  I am unable to find the origin from the step file. I don't understand where is the origin in the part  that will create problem for mapping with other parts for doing other stuff.
Please guide what to do in this case?

**Comment by tpaviot** [comment]
You can get the position/rotation matrix for each shape of the STEP file, it's available as a ```TopLoc_Location``` instance.

**Comment by Abhinav-Anil** [comment]
Thanks @tpaviot . I got the origin now using TopLoc_Location.
