### ISSUE TITLE
Missing some Python OCC module .

### ISSUE THREAD

**Issue by dev1intellial** [tpaviot/pythonocc-core#85]
In the latest version of pythonOCC-0.16.0-win32-py34 its supporting WEBGGL that's  a great one but its showing only one color and also its does not have all the module when I am going to compare this pythonOCC-0.16.0-win32-py34 with pythonOCC-0.4.win32-py2.6. 
So my questions are -
1) How to get the remaining module?
2) Is it possible to STEP file read with exact color? 
    -- Right now step file reading is possible with only one color. 
    -- Is it possible to showing exact color using STEPCAFControl this module?

**Comment by tpaviot** [comment]
STEPCAFControl is part of the latest pythonocc-0.16.1 release
