### ISSUE TITLE
Missing algorithm BRepOffsetAPI_Sewing

### ISSUE THREAD

**Issue by hbadi** [tpaviot/pythonocc-core#852]
Hi,

I cant't see the BRepOffsetAPI_Sewing class, is it a miss ?

Best regards.

**Comment by tpaviot** [comment]
yes, right, it seems it's missing

see https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_boolean_sewed_shapes.py, it should work using the last pythonocc release

**Comment by hbadi** [comment]
Great, thanks.

**Comment by hbadi** [comment]
Is there any equivalent to c++ dynamic cast operator TopoDS::Solid/Shell/... in python ?

**Comment by tpaviot** [comment]
```topods_Solid```, ```topods_Shell``` etc.

**Comment by tpaviot** [comment]
```BRepOffsetAPI_Sewing``` is just an alias for ```BRepBuilderAPI_Sewing```:

```c++
#include <BRepBuilderAPI_Sewing.hxx>
//! Sew the shapes along their common edges
typedef BRepBuilderAPI_Sewing BRepOffsetAPI_Sewing;

#endif // _BRepOffsetAPI_Sewing_HeaderFile
```
You can use the latter.
