### ISSUE TITLE
Viewer3D Display Issue

### ISSUE THREAD

**Issue by chetanjain2099** [tpaviot/pythonocc-core#861]
I am new to PythonOCC. Could you help me with few things.
I am able to display shape on the viewer, but I am having problem with few things.

- How to change the Material or color of already displayed shape. (I have multiple shape display I only want to change the Matrial or color of the shape)?
- How to change the Material or color of selected face?
- How to remove only one shape from the viewer instead of removing all?

I am not sure how to do this task. Can someone help me with this?

**Comment by tpaviot** [comment]
I suggest you take a look at the examples targetting display, see https://github.com/tpaviot/pythonocc-demos/tree/master/examples , especially the ```core_display_*``` demo scripts.
