### ISSUE TITLE
Missing GeomFill_NSections ?

### ISSUE THREAD

**Issue by adriendelsalle** [tpaviot/pythonocc-core#883]
Hi @tpaviot , thanks a lot for this great project!

I hit a problem when using `GeomFill_NSections`, it seems not available.

Did you encountered difficulties with it ? I saw the related code is [missing](https://github.com/tpaviot/pythonocc-core/blob/master/src/SWIG_files/wrapper/GeomFill.i#L9328).

Thanks!

**Comment by tpaviot** [comment]
This class ```GeomFill_NSections``` is explicitely excluded from the wrapper, see https://github.com/tpaviot/pythonocc-generator/blob/master/src/Modules.py#L304 It may be an old rule I did not update, let me check

**Comment by tpaviot** [comment]
Fixed.
