### ISSUE TITLE
How do BREP files save colors

### ISSUE THREAD

**Issue by dayhappy2012** [tpaviot/pythonocc-core#903]
How do BREP files save colors

**Comment by rainman110** [comment]
It's not possible unfortunately. You have to use the Step format.

**Comment by dayhappy2012** [comment]
ok, thanks,&nbsp;One more question

What technology do I want to do assembly with, or what key PythonOCc classes




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Martin Siggel"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 晚上7:41
收件人: "tpaviot/pythonocc-core"<pythonocc-core@noreply.github.com&gt;; 
抄送: "Y1ren"<942290627@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tpaviot/pythonocc-core] How do BREP files save colors (#903)





 
It's not possible unfortunately. You have to use the Step format.

**Comment by adam-urbanczyk** [comment]
You are interested in the following classes: `TDocStd_Document`, `XCAFDoc_DocumentTool.ShapeTool`, `XCAFDoc_DocumentTool.ColorTool`

Note that you can also save with colors in the native OCCT formats (e.g. `XmlOcaf`).
