### ISSUE TITLE
No module named 'OCC.SMESH'

### ISSUE THREAD

**Issue by JairoJs** [tpaviot/pythonocc-core#919]
Hello guys, trying to run this [example](https://github.com/tpaviot/pythonocc-core/commit/f8f37358acd378c9c4378b1b3d203c498c7a51b3) I'm getting this error:

from OCC.SMESH import SMESH_Gen
ModuleNotFoundError: No module named 'OCC.SMESH'

**Comment by tpaviot** [comment]
SMESH is not supported anymore. You can use gmsh if you need a dedicated mesher.
