### ISSUE TITLE
Linker errors for non-exported OCE classes

### ISSUE THREAD

**Issue by opticode** [tpaviot/pythonocc-core#93]
On Windows, using VS 2013 64bit, with pythonocc-core 0.16 (and OCE 0.16) I get around 20 linker errors, e.g.:

    error LNK2019: unresolved external symbol "public: __cdecl BRepMesh_CircleInspector::BRepMesh_CircleInspector(double,int,class ...
    ... referenced in function _wrap_new_BRepMesh_CircleInspector ...

On inspecting these classes, I can see that they only appear in .hxx files in the "src" directory of OCE and are *not* exported, e.g. notice the missing ```Standard_EXPORT``` from ```OCE/src/BRepMesh/BRepMesh_CircleInspector.hxx```:

    //! Implementation of inspection method
    NCollection_CellFilter_Action Inspect (const Standard_Integer theTarget); 

Should these be wrapped at all? The affected classes are:

* BRepMesh_CircleInspector
* BRepMesh_VertexInspector
* BRepMesh_Delaun
* ShapeAnalysis_BoxBndTreeSelector
* Storage_Bucket
* Storage_BucketOfPersistent
* Storage_BucketIterator

In addition, I also get this error:

    error C1091: compiler limit: string exceeds 65535 bytes in length - \Dev\pythonocc-core-0.16.0\Win64\bin\V3dPYTHON_wrap.cxx

**Comment by tpaviot** [comment]
@opticode You're right, these classes/method should not be wrapped.
