### ISSUE TITLE
old version of pythonocc on website, 0.18.1. maybe update it to most recent released version 7.4.1

### ISSUE THREAD

**Issue by Durksz** [tpaviot/pythonocc-core#931]
I just saw on the website of pythonocc that the 0.18.1 version is still marked as being the most recent released version. 
While on the github (and conda) 7.4.1 is the most recent released version.

Maybe something to update, since 0.18.1 is quite ancient...

**Comment by tpaviot** [comment]
right @Durksz , fixed !

The blog is quite inactiv for a while, I do not have enough time to maintain it as well. Anyway, there are too many outdated information, it requires a severe clean up
