### ISSUE TITLE
Where can I find the examples of Python programs in the picture below? thank you very much!

### ISSUE THREAD

**Issue by luoyu-123** [tpaviot/pythonocc-core#945]
![image](https://user-images.githubusercontent.com/59160360/101978396-87b97400-3c8f-11eb-8c25-1f66d1ac0b47.png)

**Comment by tpaviot** [comment]
Please be more specific in the issues you open on this tracker. Your question is too generale, there is not any answer ready.

Before closing this issue, my reply would be: nowhere.
