### ISSUE TITLE
How to use occ to generate a cross-sectional view and convert it into a two-dimensional engineering drawing for display, I did not find any relevant sample programs in the occ sample programs？

### ISSUE THREAD

**Issue by luoyu-123** [tpaviot/pythonocc-core#947]
I want to use occ to implement the cross-sectional view function of a three-dimensional object, and mark the data on the cross-section, the effect is the same as the picture below, but I did not find the relevant sample program？
thank you very much！！

![image](https://user-images.githubusercontent.com/59160360/102032468-cd8f4d00-3df3-11eb-8da4-e51767a87551.png)

**Comment by tpaviot** [comment]
You can combine https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_display_clip_planes.py and https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_dimensions.py

**Comment by OkanPinar** [comment]
For creating 2D drawing from 3D object  HLRBRep_PolyAlgo and BRepAlgoAPI_Section classes can be useful also.

**Comment by luoyu-123** [comment]
thank you

**Comment by Bill-XU** [comment]
> thank you

@luoyu-123 
Hello, have you implemented "mark the data on the cross-section"?
Curious about how to determine the edges to measure and mark the data.

Best regards,
Bill
