### ISSUE TITLE
A Error

### ISSUE THREAD

**Issue by YexiangYan** [tpaviot/pythonocc-core#950]
Hello, I am a new hand，when I run a demo,
The error is :
Aspect_GraphicDeviceDefinitionErrorOpenGl_Window::CreateWindow: SetPixelFormat failed. Error code: 2000 raised from method Init of class Display3d

How to solve it ?   Thanks!

**Comment by tpaviot** [comment]
which pythonocc version do you use?

**Comment by tpaviot** [comment]
This should be fixed by commit a028f6063fb1f2506d7ab42802f565c74019d1e7
