### ISSUE TITLE
core_visualization_overpaint_viewer cannot run properly after upgrade to 7.4.1

### ISSUE THREAD

**Issue by geraldozzz** [tpaviot/pythonocc-core#952]
hi, 
I can run this example with pythonocc 7.4.0, but when upgraded it to 7.4.1, no bubble shows on the screen anymore. Moreover, some of my code to draw line and image stop working too. It can be fixed by comment out below code in the qtDisplay, but I am not sure if it's the right way.

BTW, it also affected the DrawBox functionality

```
 def paintEngine(self):
        return None 
```

**Comment by tpaviot** [comment]
This example is not supported anymore. The base class for the qtViewer3d has recently been moved to a classical QWidget that does not support double buffering calls.
