### ISSUE TITLE
Installing OCC offline 

### ISSUE THREAD

**Issue by syigit61** [tpaviot/pythonocc-core#954]
I need to use BladeX in offline computer. Is it possible to install OCC module offline dependency ? I would be grateful if you could help me.

**Comment by OkanPinar** [comment]
You can fallow the steps that are described in following link.

https://github.com/tpaviot/pythonocc-core/blob/master/INSTALL.md

**Comment by tpaviot** [comment]
Can you please elaborate on what you mean with "offline installation" ?

**Comment by syigit61** [comment]
OCC ask many dependencies, my question is on is there any way to install OCC on computer without internet ?

On 30 Jan 2021, at 09:30, Thomas Paviot <notifications@github.com> wrote:

﻿

Can you please elaborate on what you mean with "offline installation" ?

**Comment by tpaviot** [comment]
It's not a pythonocc related question I guess. Rather something related to conda. Without additional information, I suggest to create a conda installation on a first machine, then simply copy/paste the environment to the other machine.
