### ISSUE TITLE
Where can I download another package ocp of Pythonocc?

### ISSUE THREAD

**Issue by luoyu-123** [tpaviot/pythonocc-core#957]
![image](https://user-images.githubusercontent.com/59160360/105798794-ea5f9880-5fcd-11eb-8481-081c0061350d.png)

**Comment by adam-urbanczyk** [comment]
OCP is not affiliated with PythonOCC, please use the correct issue tracker. With that being said, you can use conda to install:
```
conda install -c conda-forge -c cadquery ocp
```

**Comment by luoyu-123** [comment]
thank you
