### ISSUE TITLE
WXDisplay error Init driver throwing error

### ISSUE THREAD

**Issue by Durksz** [tpaviot/pythonocc-core#959]
I've updated the python OCC version (version 7.4.1, PY37hc019675_0), and encountered an issue.

The WXdisplay initialization fails:

The error is: that the OCCViewer.Viewer3d(self.GetWinId()) receives two variables while one is accepted.

The solution is moving the self.GetWinId() to the display.Create:

```
    def InitDriver(self):
        self._display = OCCViewer.Viewer3d()
        self._display.Create(self.GetWinId())
        self._display.SetModeShaded()
        self._inited = True
```

This solves it for me.

**Comment by tpaviot** [comment]
Thank you for your report, this issue is already fixed in master branch
