### ISSUE TITLE
Aspect_DriverDefinitionError

### ISSUE THREAD

**Issue by HuntForRedOctober** [tpaviot/pythonocc-core#96]
When running any of the examples I get the following error regardless of the backend I specify

C:\Users\xxxx\Downloads\pythonocc-core-0.16.0\examples>python core_geometry_airfoil.py
###### 3D rendering pipe initialisation #####
Display3d class initialization starting ...
Aspect_DisplayConnection created.
Traceback (most recent call last):
  File "core_geometry_airfoil.py", line 107, in <module>
    display, start_display, add_menu, add_function_to_menu = init_display('wx')
  File "C:\Users\xxxx\Programs\pythonxy\python27\lib\site-packages\OCC\Display\SimpleGui.py", line 95, in init_display

    win.canva.InitDriver()
  File "C:\Users\xxxx\Programs\pythonxy\python27\lib\site-packages\OCC\Display\wxDisplay.py", line 108, in InitDriver
    self._display.Create()
  File "C:\Users\xxxx\Programs\pythonxy\python27\lib\site-packages\OCC\Display\OCCViewer.py", line 105, in Create
    self.Init(self._window_handle)
RuntimeError: Aspect_DriverDefinitionError
The specified module could not be found.

I'm using:
pythonOCC-0.16.0-win32-py27
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
('Qt version:', '4.8.4')
('SIP version:', '4.14.2')
('PyQt version:', '4.9.6')
PySide 1.2.2
Wx 2.8

Any Idea?
I have used the pythonOCC-0.16.0-win32-py27.exe installer on a different machine to decompress and I have copied over the OCC folder to the sitepackages folder of my python installation. Could this be a problem?

**Comment by tpaviot** [comment]
This is an issue with the OpenGL driver. But sure your graphic card driver is up-to-date. Which card model is it ?

**Comment by HuntForRedOctober** [comment]
I have a nvidia Quadro 3000M, about 3-4 years old by now. The drivers should be reasonably up-to-date..
Thanks for your help
Stefano

**Comment by jf---** [comment]
Sounds like XQuartz / X11 is not running...
On which platform are you running, please state the pythonocc / OCE version...
Thanks

**Comment by HuntForRedOctober** [comment]
I’m actually running on windows 7 using OCE 0.16.1 and python-occ 0.16.0

**Comment by neerajs71** [comment]
I have the same problem on Windows-7. Running on Sony I5 Viao. RADEON Graphics driver.

**Comment by neerajs71** [comment]
Is there any resolution to the issue? Any advice?

**Comment by Rebbirobbe** [comment]
Hello, 

we got the same error on Windows 7 (64bit and 32bit).. 
(we tried to run the OCC-Box-example) 
but it seems that we have found the solution.
We had to set an environment variable for system:
CSF_GraphicShr=c:\py27\Lib\site-packages\OCC\libTKOpenGl.dll
(we use Python X,Y)
During the installation an environment variable is set, but only for the user who installed the software.

Greetings

**Comment by tpaviot** [comment]
@Rebbirobbe That's the point actually, I forgot about that! @HuntForRedOctober can you please test that ? I may have to fix the installer script so that this environnement variable, on Windows, is set for all users.

**Comment by HuntForRedOctober** [comment]
I tried with the environmental variable, but it didn’t work out..

But…

I copied all the dlls from the OCC folder in the site packages to the main python folder… and then it worked out OK..

**Comment by tpaviot** [comment]
@HuntForRedOctober Ok, thanks for the tip. OCE dlls are installed to the site-packages/OCC directory, the same folder than the .py modules. It works on most machines, I didn't know it can be a problem.
