### ISSUE TITLE
Step file importer only imports shape but not path on shape

### ISSUE THREAD

**Issue by Thieso** [tpaviot/pythonocc-core#965]
Hello, 

I would like to import a step file with a shape and a path on that shape. In FreeCAD that works as intented as shown here:
![Screenshot from 2021-02-17 14-15-25](https://user-images.githubusercontent.com/15210390/108209488-a70acc80-712a-11eb-9b4e-ae66b7a6b8cb.png)

However when I import the file in pythonocc and show it, it does not show the path on the surface, see here:
![Screenshot from 2021-02-17 14-17-06](https://user-images.githubusercontent.com/15210390/108209656-d7526b00-712a-11eb-8205-df6b55a8fb67.png)

I use this code to display the file 

```
import os.path
from IPython.core.display import SVG
from OCC.Display.WebGl.jupyter_renderer import JupyterRenderer
from OCC.Extend.DataExchange import read_step_file

shp = read_step_file(os.path.join(<path to stp file>)
my_renderer = JupyterRenderer(size=(800,700))
my_renderer.DisplayShape(shp, render_edges=True)
my_renderer.Display()
```

Can you tell me why this does not work and how to fix it? 

Thanks a lot

**Comment by JorisCodde** [comment]
Maybe it's a display issue and not a step importer issue ?

What's in the shp variable ?

**Comment by Thieso** [comment]
It is a object of <class 'TopoDS_Compound'>, or what do you mean?
