### ISSUE TITLE
how do i close SimpleGUI window?

### ISSUE THREAD

**Issue by RobinVanTol** [tpaviot/pythonocc-core#972]
The win object in the init display function does not get returned and there is also no method made to close the window. Im using pyQt5 as backend which has the close function, so in init_display win.close() would close the window, however i dont see any way to do this with what init_display returns.

Is there a way to close the window?

**Comment by tpaviot** [comment]
```python
sys.exit() # this will close the window, for sure
``` 
😃

**Comment by RobinVanTol** [comment]
I mean, well yes, but i only want to close the simplegui window, not the entire program

**Comment by tpaviot** [comment]
This is a PyQt5 development issue. Don't use the SimpleGui, but build your own gui using the qtViewer3d widget.
