### ISSUE TITLE
assembly solver

### ISSUE THREAD

**Issue by dayhappy2012** [tpaviot/pythonocc-core#973]
Hello, may I ask how to implement the assembly solver? Can you provide some ideas?

**Comment by tpaviot** [comment]
That's a big deal, this requires tough work. I guess the cadquery guys already did something similar, see https://github.com/CadQuery/cadquery/blob/c0ebebab44fdc09adaf7eed020facdf7a7106120/cadquery/assembly.py

**Comment by tpaviot** [comment]
Support for assemblies is not planned.
