### ISSUE TITLE
Intersection Between Two Shapes

### ISSUE THREAD

**Issue by Vahid44** [tpaviot/pythonocc-core#975]
Hello everyone,
Is there any way to find out if the intersection between two shapes is Null or not? (see the result as a boolean)
I searched "TopologyExplorer" and "BRepAlgoAPI_Section" but none of them has a specific function for this purpose.

Thanks,
Vahid

**Comment by Vahid44** [comment]
Hello @OkanPinar,
Do you know any function for this issue?

**Comment by tpaviot** [comment]
Have a look at the example https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_topology_boolean.py

**Comment by Vahid44** [comment]
Thank you very much dear @tpaviot.
Actually, I searched this page but couldn't find a specific function for my problem.

I know this can be done by using other functions. For example, using BRepAlgoAPI_Section and TopologyExplorer and see if the Section has any edges, points, etc.

But I was wondering if there is any particular function for solving this problem since I guess it would be very useful in many cases.

Regards,
Vahid

**Comment by tpaviot** [comment]
IMO the most robust way to check for intersections between two shapes is to mesh both shapes to a triangular mesh and use a mesh library to perform boolean operations/minimum distance (e.g. trimesh).

**Comment by Vahid44** [comment]
Thank you dear @tpaviot

I'm working with IFC objects and use pythonocc to define objects' shapes. 
Is that possible to use trimesh for meshing OCC shapes? 
Or I need to use other meshing libraries, like SMESH (I don't know if it is still supported by pythonocc or not.)

**Comment by tpaviot** [comment]
You can use the builtin pythonocc mesher or a third one (I use to work with gmsh when accurate meshes are needed).
