### ISSUE TITLE
Need Help on module PrsDim 

### ISSUE THREAD

**Issue by YihaiWei** [tpaviot/pythonocc-core#978]
Hi! Nice to meet your guys! Recently, i meet some problem about how to constrain the degree of freedom in linkage motion.
When I look up the information on the website:
https://dev.opencascade.org/doc/refman/html/toolkit_tkv3d.html
 I find that this module PrsDim is missing in pythonocc. Can I find this module or modules with similar functions in pythonocc ?

**Comment by tpaviot** [comment]
The PrsDim is actually wrapped in the current master branch. Which pythonocc version do you use?

**Comment by YihaiWei** [comment]
thank you very much. I have found the corresponding module---such as "AIS_Relation"
Thanks again
