### ISSUE TITLE
shapes recognition

### ISSUE THREAD

**Issue by alexinteam** [tpaviot/pythonocc-core#979]
Hi! I'm trying to identify objects in my model. How can I do this? I discovered examples and identifing holes is clear for me. But what should be done if Object I want to discover is consists of several plain, ex. parallelepiped.  
![Безымянный](https://user-images.githubusercontent.com/8863763/111472644-38c22580-873b-11eb-85a8-e3c4a10f3a85.png)
PS. I make my model from step file

**Comment by tpaviot** [comment]
Have a look at the example https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_geometry_recognize_feature.py

**Comment by alexinteam** [comment]
Hello!, Thanks for the advice. I did, but still I'm wondering if it possible to detect cube hole. Cube hole is a List of plane faces. Is there algoritm to concat those faces and recognize that it is cube hole?

**Comment by tpaviot** [comment]
There's not an out-of-the-box algorithm, but all the bases are available to build what you need.

**Comment by alexinteam** [comment]
Thank you
