### ISSUE TITLE
DynamicType of a curve

### ISSUE THREAD

**Issue by e3dEF** [tpaviot/pythonocc-core#983]
How can I check, whether a curve is e.g. Geom_LIne or Geom_Conic (and it's subtypes).

I tested BRep_Tool_Curve(edge)[0].DynamicType(), which returns an <Swig Object of type 'opencascade::handle< Standard_Type > and BRepAdaptor_Curve(edge).Curve() which has no DynamicType().

I tested as alternative to this: [OCCUtils](https://github.com/tpaviot/pythonocc-utils/issues/26)

**Comment by tpaviot** [comment]
Have a look at https://github.com/tpaviot/pythonocc-demos/blob/master/examples/core_geometry_recognize_feature.py

**Comment by e3dEF** [comment]
I will have a look
