### ISSUE TITLE
next release pythonocc-ore 7.5.2 and occt-7.5.2

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-core#995]
@looooo I noticed that a new occt version has been tagged (https://git.dev.opencascade.org/gitweb/?p=occt.git;a=commit;h=0dc2c377fc5a2d8cf065f4ec005e356240cb484c). Is there any plan at conda-forge to move occt up to 7.5.2?

**Comment by looooo** [comment]
I read about some issues with that version:
https://forum.freecadweb.org/viewtopic.php?f=4&t=58090

**Comment by tpaviot** [comment]
Interesting point, thank you.

**Comment by tpaviot** [comment]
I would like to release a bugfix version for pythonocc-core, but if I upgrade the pythonocc version to 7.5.2, there might be confusion with the occt release. Any suggestion?

**Comment by looooo** [comment]
7.5.1.1 ? not very convenient, but we did the same with smesh recently:
https://github.com/conda-forge/smesh-feedstock/blob/master/recipe/meta.yaml#L2

**Comment by tpaviot** [comment]
That makes sense

**Comment by looooo** [comment]
@tpaviot do we have to pin occt in the pythonocc-feedstock to the patch version of occt? Currently, only the minor version (x.x) is used for the pinning.

We will update to occt7.5.2 soon. So I guess you can release pythonocc also as 7.5.2.

**Comment by tpaviot** [comment]
@looooo Ok, the current pythonocc-core release (7.5.1) should not be updated to 7.5.2

As soon as occt-7.5.2 is available at conda-forge, I will update pythonocc as well (there might be some API changes that require the python wrapper to be updated). I will notify you as soon as the move up to 7.5.2 is ready. Thank you for your help.

**Comment by tpaviot** [comment]
There will not be any 7.5.2 version for pythonocc-core, let's move to 7.5.3 @looooo

**Comment by tpaviot** [comment]
superseded by #1067
